/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IST261DesktopPaneDemo;

import java.sql.Connection;

/**
 *
 * @author Nathan
 */
public class jpAddAssignment extends javax.swing.JPanel {

    /**
     * Creates new form jpAssignment
     */
        private Connection dbConnection;
        public jpAddAssignment(Connection inConnection)
        {
            initComponents();
            dbConnection = inConnection;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAssignmentName = new javax.swing.JLabel();
        jtfAssignmentName = new javax.swing.JTextField();
        jchbGroupAssignment = new javax.swing.JCheckBox();
        jbAddAssignmentFinish = new javax.swing.JButton();
        jlPoints = new javax.swing.JLabel();
        jtfPoints = new javax.swing.JTextField();
        jlDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescription = new javax.swing.JTextArea();

        jlAssignmentName.setText("Name");

        jchbGroupAssignment.setText("Group Assignment");
        jchbGroupAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchbGroupAssignmentActionPerformed(evt);
            }
        });

        jbAddAssignmentFinish.setText("Finsih");
        jbAddAssignmentFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddAssignmentFinishActionPerformed(evt);
            }
        });

        jlPoints.setText("Points");

        jlDescription.setText("Description");

        jtaDescription.setColumns(20);
        jtaDescription.setRows(5);
        jScrollPane1.setViewportView(jtaDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlDescription)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlPoints)
                        .addComponent(jlAssignmentName)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAddAssignmentFinish)
                    .addComponent(jtfPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAssignmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchbGroupAssignment)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfAssignmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jlPoints))
                    .addComponent(jlAssignmentName))
                .addGap(18, 18, 18)
                .addComponent(jchbGroupAssignment)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDescription)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbAddAssignmentFinish)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddAssignmentFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddAssignmentFinishActionPerformed
        this.getTopLevelAncestor().setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAddAssignmentFinishActionPerformed

    private void jchbGroupAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchbGroupAssignmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchbGroupAssignmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAddAssignmentFinish;
    private javax.swing.JCheckBox jchbGroupAssignment;
    private javax.swing.JLabel jlAssignmentName;
    private javax.swing.JLabel jlDescription;
    private javax.swing.JLabel jlPoints;
    private javax.swing.JTextArea jtaDescription;
    private javax.swing.JTextField jtfAssignmentName;
    private javax.swing.JTextField jtfPoints;
    // End of variables declaration//GEN-END:variables
}
