/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IST261DesktopPaneDemo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;

/**
 *
 * @author Nathan
 */
public class jpAddResources extends javax.swing.JPanel {

    /**
     * Creates new form jpAddResources
     */
    private Connection dbConnection; //database connection passed from jpCourse
    private PreparedStatement pst;
    private Statement st;
    
    private String strDescription = null;
    public jpAddResources() {
        initComponents();
    }
    public jpAddResources(Connection inConnection){
        initComponents();
        dbConnection = inConnection;
    }// jpAddAssignment
    
    // This sets description area based on user input.
    private void setDescription(JTextArea injtaDescription){
        strDescription = injtaDescription.getText();
    }// setDescription
    
    private void InsertToTable(String inDescription){
        try {
            String query = "INSERT INTO Resources ( Description )"
                    + " VALUES (?)";//8
             pst = dbConnection.prepareStatement(query);
             pst.setString(1, inDescription);
             pst.execute();
        } catch (SQLException ex) {
            Logger.getLogger(jpAddResources.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Failed");
        }// try/catch
        
    }// insertToTable
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescription = new javax.swing.JTextArea();
        jbAddResource = new javax.swing.JButton();

        jLabel1.setText("Description");

        jtaDescription.setColumns(20);
        jtaDescription.setRows(5);
        jScrollPane1.setViewportView(jtaDescription);

        jbAddResource.setText("Add Resource");
        jbAddResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddResourceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAddResource)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbAddResource)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddResourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddResourceActionPerformed
        setDescription(jtaDescription);
        InsertToTable(strDescription);
        this.getTopLevelAncestor().setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAddResourceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAddResource;
    private javax.swing.JTextArea jtaDescription;
    // End of variables declaration//GEN-END:variables
}
