/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IST261DesktopPaneDemo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Nathan
 */
public class jpAddClass extends javax.swing.JPanel {

    /**
     * Creates new form jpAddClass
     */
    private Connection dbConnection;
    private Statement st;
    private PreparedStatement pst;
    private String[] Times;
    // variables that get passed to the database
    private int intCourse;
    private String strCampus;
    private String strMeetingLocation;
    private int intSection;
    private int intScheduleNumber;
    private String strAngelID;
    private String strAngelTitle;
    private String strNotes;
    private String strMondayStart;
    private String strTuesdayStart;
    private String strWednesdayStart;
    private String strThursdayStart;
    private String strFridayStart;
    private String strSaturdayStart;
    private String strSundayStart;
    private String strMondayEnd;
    private String strTuesdayEnd;
    private String strWednesdayEnd;
    private String strThursdayEnd;
    private String strFridayEnd;
    private String strSaturdayEnd;
    private String strSundayEnd;
    
    public jpAddClass() {
        initComponents(); 
    }

    jpAddClass(Connection inConnection) {
        initComponents();
        setdbConnection(inConnection);
        setjcbCourse();
        setjcbCampus();
        setStartFinish();
        
        
        
        //     throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAddClassFinish = new javax.swing.JButton();
        jlMeetingLocation = new javax.swing.JLabel();
        jtfMeetingLocation = new javax.swing.JTextField();
        jlSection = new javax.swing.JLabel();
        jlScheduleNumber = new javax.swing.JLabel();
        jtfSection = new javax.swing.JTextField();
        jlAngelID = new javax.swing.JLabel();
        jlAngelTitle = new javax.swing.JLabel();
        jtfScheduleNumber = new javax.swing.JTextField();
        jtfAngelID = new javax.swing.JTextField();
        jtfAngelTitle = new javax.swing.JTextField();
        jlCourse = new javax.swing.JLabel();
        jcbCourse = new javax.swing.JComboBox();
        jchbMonday = new javax.swing.JCheckBox();
        jchbTuesday = new javax.swing.JCheckBox();
        jchbWednesday = new javax.swing.JCheckBox();
        jchbThursday = new javax.swing.JCheckBox();
        jchbFriday = new javax.swing.JCheckBox();
        jchbSaturday = new javax.swing.JCheckBox();
        jchbSunday = new javax.swing.JCheckBox();
        jlMeetingDays = new javax.swing.JLabel();
        jlStartTime = new javax.swing.JLabel();
        jlEndTime = new javax.swing.JLabel();
        jcbMondayStart = new javax.swing.JComboBox();
        jcbMondayEnd = new javax.swing.JComboBox();
        jlMondayTo = new javax.swing.JLabel();
        jcbTuesdayStart = new javax.swing.JComboBox();
        jcbWednesdayStart = new javax.swing.JComboBox();
        jcbThursdayStart = new javax.swing.JComboBox();
        jcbFridayStart = new javax.swing.JComboBox();
        jcbSaturdayStart = new javax.swing.JComboBox();
        jcbSundayStart = new javax.swing.JComboBox();
        jcbTuesdayEnd = new javax.swing.JComboBox();
        jcbWednesdayEnd = new javax.swing.JComboBox();
        jcbThursdayEnd = new javax.swing.JComboBox();
        jcbFridayEnd = new javax.swing.JComboBox();
        jcbSaturdayEnd = new javax.swing.JComboBox();
        jcbSundayEnd = new javax.swing.JComboBox();
        jlTuesdayTo = new javax.swing.JLabel();
        jlWednesdayTo = new javax.swing.JLabel();
        jlThursdayTo = new javax.swing.JLabel();
        jlFridayTo = new javax.swing.JLabel();
        jlSaturdayTo = new javax.swing.JLabel();
        jlSundayTo = new javax.swing.JLabel();
        jlNotes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaNotes = new javax.swing.JTextArea();
        jlCampus = new javax.swing.JLabel();
        jcbCampus = new javax.swing.JComboBox();

        jbAddClassFinish.setText("Finish");
        jbAddClassFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddClassFinishActionPerformed(evt);
            }
        });

        jlMeetingLocation.setText("Meeting Location");

        jlSection.setText("Section");

        jlScheduleNumber.setText("Schedule Number");

        jlAngelID.setText("ANGEL ID");

        jlAngelTitle.setText("ANGLE Title");

        jlCourse.setText("Course");

        jcbCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jchbMonday.setText("Monday");
        jchbMonday.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jchbMondayStateChanged(evt);
            }
        });

        jchbTuesday.setText("Tuesday");
        jchbTuesday.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jchbTuesdayStateChanged(evt);
            }
        });

        jchbWednesday.setText("Wednesday");
        jchbWednesday.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jchbWednesdayStateChanged(evt);
            }
        });

        jchbThursday.setText("Thursday");
        jchbThursday.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jchbThursdayStateChanged(evt);
            }
        });

        jchbFriday.setText("Friday");
        jchbFriday.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jchbFridayStateChanged(evt);
            }
        });

        jchbSaturday.setText("Saturday");
        jchbSaturday.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jchbSaturdayStateChanged(evt);
            }
        });

        jchbSunday.setText("Sunday");
        jchbSunday.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jchbSundayStateChanged(evt);
            }
        });

        jlMeetingDays.setText("Meeting Days");

        jlStartTime.setText("Start");

        jlEndTime.setText("End");

        jcbMondayStart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbMondayStart.setEnabled(false);

        jcbMondayEnd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbMondayEnd.setEnabled(false);

        jlMondayTo.setText("to");

        jcbTuesdayStart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbTuesdayStart.setEnabled(false);

        jcbWednesdayStart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbWednesdayStart.setEnabled(false);

        jcbThursdayStart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbThursdayStart.setEnabled(false);

        jcbFridayStart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbFridayStart.setEnabled(false);

        jcbSaturdayStart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbSaturdayStart.setEnabled(false);

        jcbSundayStart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbSundayStart.setEnabled(false);

        jcbTuesdayEnd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbTuesdayEnd.setEnabled(false);

        jcbWednesdayEnd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbWednesdayEnd.setEnabled(false);

        jcbThursdayEnd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbThursdayEnd.setEnabled(false);

        jcbFridayEnd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbFridayEnd.setEnabled(false);

        jcbSaturdayEnd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbSaturdayEnd.setEnabled(false);

        jcbSundayEnd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbSundayEnd.setEnabled(false);

        jlTuesdayTo.setText("to");

        jlWednesdayTo.setText("to");

        jlThursdayTo.setText("to");

        jlFridayTo.setText("to");

        jlSaturdayTo.setText("to");

        jlSundayTo.setText("to");

        jlNotes.setText("Notes");

        jtaNotes.setColumns(20);
        jtaNotes.setRows(5);
        jScrollPane1.setViewportView(jtaNotes);

        jlCampus.setText("Campus");

        jcbCampus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlCourse)
                            .addComponent(jlCampus)
                            .addComponent(jlMeetingLocation)
                            .addComponent(jlSection)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlScheduleNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlAngelID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlAngelTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlNotes, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbAddClassFinish)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(102, 102, 102))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfMeetingLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSection, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfScheduleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfAngelID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfAngelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlMeetingDays)
                            .addComponent(jchbMonday)
                            .addComponent(jchbTuesday)
                            .addComponent(jchbWednesday)
                            .addComponent(jchbThursday)
                            .addComponent(jchbFriday)
                            .addComponent(jchbSaturday)
                            .addComponent(jchbSunday))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbSundayStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbSundayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbSaturdayStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbSaturdayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbFridayStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbFridayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbThursdayStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbThursdayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbWednesdayStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbWednesdayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcbTuesdayStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbTuesdayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlStartTime)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcbMondayStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlTuesdayTo)
                                            .addComponent(jlMondayTo)
                                            .addComponent(jlWednesdayTo)
                                            .addComponent(jlThursdayTo)
                                            .addComponent(jlFridayTo)
                                            .addComponent(jlSaturdayTo)
                                            .addComponent(jlSundayTo))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbMondayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlEndTime))))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlMeetingDays)
                            .addComponent(jlStartTime)
                            .addComponent(jlEndTime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jchbMonday)
                            .addComponent(jcbMondayStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbMondayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlMondayTo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jchbTuesday)
                            .addComponent(jcbTuesdayStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbTuesdayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlTuesdayTo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jchbWednesday)
                            .addComponent(jcbWednesdayStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbWednesdayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlWednesdayTo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jchbThursday)
                            .addComponent(jcbThursdayStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbThursdayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlThursdayTo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jchbFriday)
                            .addComponent(jcbFridayStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbFridayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlFridayTo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jchbSaturday)
                            .addComponent(jcbSaturdayStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbSaturdayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlSaturdayTo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jchbSunday)
                            .addComponent(jcbSundayStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbSundayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlSundayTo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCourse)
                            .addComponent(jcbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCampus)
                            .addComponent(jcbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfMeetingLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlMeetingLocation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSection)
                            .addComponent(jtfSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlScheduleNumber)
                            .addComponent(jtfScheduleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlAngelID)
                            .addComponent(jtfAngelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlAngelTitle)
                            .addComponent(jtfAngelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlNotes)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAddClassFinish))
        );
    }// </editor-fold>//GEN-END:initComponents
   
    private void setCourse(JComboBox injcbCourse){
        intCourse = Integer.parseInt( injcbCourse.getSelectedItem()+"");
    }

    private void setCampus(JComboBox injcbCampus){
        strCampus = injcbCampus.getSelectedItem()+"";
    }
    private void setMeetingLocation(JTextField injtfMeetingLocation){
        strMeetingLocation = injtfMeetingLocation.getText();
    }
    private void setSection(JTextField injtfSection){
        intSection = Integer.parseInt(injtfSection.getText());
    }
    private void setScheduleNumber(JTextField injtfScheduleNumber){
        intScheduleNumber = Integer.parseInt(injtfScheduleNumber.getText());
    }
    private void setAngelID(JTextField injtfAngelID){
        strAngelID = injtfAngelID.getText();
    }
    private void setAngelTitle(JTextField injtfAngelTitle){
        strAngelTitle = injtfAngelTitle.getText();
    }
    private void setNotes(JTextArea injtaNotes){
        strNotes = injtaNotes.getText();
    }
    private void setMondayStart(JComboBox injcbMondayStart){
        if(jchbMonday.isSelected()){
            strMondayStart = injcbMondayStart.getSelectedItem()+"";
        }
        else{
            strMondayStart = null;
        }
    }
    private void setMondayEnd(JComboBox injcbMondayEnd){
        if(jchbMonday.isSelected()){
            strMondayEnd = injcbMondayEnd.getSelectedItem()+"";
        }
        else{
            strMondayStart = null;
        }
    }
    private void setTuesdayStart(JComboBox injcbTuesdayStart){
        if(jchbTuesday.isSelected()){
            strTuesdayStart = injcbTuesdayStart.getSelectedItem()+"";
        }
        else{
            strTuesdayStart = null;
        }
    }
    private void setTuesdayEnd(JComboBox injcbTuesdayEnd){
        if(jchbTuesday.isSelected()){
            strTuesdayEnd = injcbTuesdayEnd.getSelectedItem()+"";
        }
        else{
            strTuesdayStart = null;
        }
    }
    private void setWednesdayStart(JComboBox injcbWednesdayStart){
        if(jchbWednesday.isSelected()){
            strWednesdayStart = injcbWednesdayStart.getSelectedItem()+"";
        }
        else{
            strWednesdayStart = null;
        }
    }
    private void setWednesdayEnd(JComboBox injcbWednesdayEnd){
        if(jchbWednesday.isSelected()){
            strWednesdayEnd = injcbWednesdayEnd.getSelectedItem()+"";
        }
        else{
            strWednesdayStart = null;
        }
    }
    private void setThursdayStart(JComboBox injcbThursdayStart){
        if(jchbThursday.isSelected()){
            strThursdayStart = injcbThursdayStart.getSelectedItem()+"";
        }
        else{
            strThursdayStart = null;
        }
    }
    private void setThursdayEnd(JComboBox injcbThursdayEnd){
        if(jchbThursday.isSelected()){
            strThursdayEnd = injcbThursdayEnd.getSelectedItem()+"";
        }
        else{
            strThursdayStart = null;
        }
    }
    private void setFridayStart(JComboBox injcbFridayStart){
        if(jchbFriday.isSelected()){
            strFridayStart = injcbFridayStart.getSelectedItem()+"";
        }
        else{
            strFridayStart = null;
        }
    }
    private void setFridayEnd(JComboBox injcbFridayEnd){
        if(jchbFriday.isSelected()){
            strFridayEnd = injcbFridayEnd.getSelectedItem()+"";
        }
        else{
            strFridayStart = null;
        }
    }
    private void setSaturdayStart(JComboBox injcbSaturdayStart){
        if(jchbSaturday.isSelected()){
            strSaturdayStart = injcbSaturdayStart.getSelectedItem()+"";
        }
        else{
            strSaturdayStart = null;
        }
    }
    private void setSaturdayEnd(JComboBox injcbSaturdayEnd){
        if(jchbSaturday.isSelected()){
            strSaturdayEnd = injcbSaturdayEnd.getSelectedItem()+"";
        }
        else{
            strSaturdayStart = null;
        }
    }
    private void setSundayStart(JComboBox injcbSundayStart){
        if(jchbSunday.isSelected()){
            strSundayStart = injcbSundayStart.getSelectedItem()+"";
        }
        else{
            strSundayStart = null;
        }
    }
    private void setSundayEnd(JComboBox injcbSundayEnd){
        if(jchbSunday.isSelected()){
            strSundayEnd = injcbSundayEnd.getSelectedItem()+"";
        }
        else{
            strSundayStart = null;
        }
    }
    
    
// This sets the local datbase connection
    private void setdbConnection(Connection inConnection){
        dbConnection = inConnection;
        try {
             
            st = dbConnection.createStatement();
            
 
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    
// This populates the Course drop down box
    private void setjcbCourse(){
        jcbCourse.removeAllItems();
        jcbCourse.addItem("Please Select...");
 
        try {
             
            ResultSet rs = st.executeQuery("select Number from Course order by Number asc");

            while (rs.next()) {
                jcbCourse.addItem(//rs.getString("IST") + " " + 
                        rs.getString("Number"));
            }
        } catch (SQLException sqle) {
            System.out.println(sqle);
        }
    }
    
//This populates the Campus drop down box. 
    private void setjcbCampus(){
        jcbCampus.removeAllItems();
        jcbCampus.addItem("Please Select...");
 
        try {
             
            ResultSet rs = st.executeQuery("select CampusName from Campus order by CampusName asc");

            while (rs.next()) {
                jcbCampus.addItem(//rs.getString("IST") + " " + 
                        rs.getString("CampusName"));
            }
        } catch (SQLException sqle) {
            System.out.println(sqle);
        }
    }
    
// This sets all the State and Finish drop down times for the each day of the week
    private void setStartFinish(){
        Times = new String [] 
        {
            "8:00","8:05","8:10","8:15","8:20","8:25","8:30","8:35","8:40","8:45","8:50","8:55",
            "9:00","9:05","9:10","9:15","9:20","9:25","9:30","9:35","9:40","9:45","9:50","9:55",
            "10:00","10:05","10:10","10:15","10:20","10:25","10:30","10:35","10:40","10:45","10:50","10:55",
            "11:00","11:05","11:10","11:15","11:20","11:25","11:30","11:35","11:40","11:45","11:50","11:55",
            "12:00","12:05","12:10","12:15","12:20","12:25","12:30","12:35","12:40","12:45","12:50","12:55",
            "1:00","1:05","1:10","1:15","1:20","1:25","1:30","1:35","1:40","1:45","1:50","1:55",
            "2:00","2:05","2:10","2:15","2:20","2:25","2:30","2:35","2:40","2:45","2:50","2:55",
            "3:00","3:05","3:10","3:15","3:20","3:25","3:30","3:35","3:40","3:45","3:50","3:55",
            "4:00","4:05","4:10","4:15","4:20","4:25","4:30","4:35","4:40","4:45","4:50","4:55",
            "5:00","5:05","5:10","5:15","5:20","5:25","5:30","5:35","5:40","5:45","5:50","5:55",
            "6:00","6:05","6:10","6:15","6:20","6:25","6:30","6:35","6:40","6:45","6:50","6:55",
            "7:00","7:05","7:10","7:15","7:20","7:25","7:30","7:35","7:40","7:45","7:50","7:55",
            "8:00","8:05","8:10","8:15","8:20","8:25","8:30","8:35","8:40","8:45","8:50","8:55",
            "9:00","9:05","9:10","9:15","9:20","9:25","9:30","9:35","9:40","9:45","9:50","9:55",
            "10:00","10:05","10:10","10:15","10:20","10:25","10:30","10:35","10:40","10:45","10:50","10:55"
        };
        jcbMondayStart.removeAllItems();
        jcbTuesdayStart.removeAllItems();
        jcbWednesdayStart.removeAllItems();
        jcbThursdayStart.removeAllItems();
        jcbFridayStart.removeAllItems();
        jcbSaturdayStart.removeAllItems();
        jcbSundayStart.removeAllItems();
        jcbMondayEnd.removeAllItems();
        jcbTuesdayEnd.removeAllItems();
        jcbWednesdayEnd.removeAllItems();
        jcbThursdayEnd.removeAllItems();
        jcbFridayEnd.removeAllItems();
        jcbSaturdayEnd.removeAllItems();
        jcbSundayEnd.removeAllItems();
        for (int i=0;i<Times.length;i++){
            jcbMondayStart.addItem(Times[i]);
            jcbTuesdayStart.addItem(Times[i]);
            jcbWednesdayStart.addItem(Times[i]);
            jcbThursdayStart.addItem(Times[i]);
            jcbFridayStart.addItem(Times[i]);
            jcbSaturdayStart.addItem(Times[i]);
            jcbSundayStart.addItem(Times[i]);
            jcbMondayEnd.addItem(Times[i]);
            jcbTuesdayEnd.addItem(Times[i]);
            jcbWednesdayEnd.addItem(Times[i]);
            jcbThursdayEnd.addItem(Times[i]);
            jcbFridayEnd.addItem(Times[i]);
            jcbSaturdayEnd.addItem(Times[i]);
            jcbSundayEnd.addItem(Times[i]);
        }
    }
    
//This gets the course Id by passing it the course number.
    private int getCourseID(int inCourse){
        ResultSet rs;
        int intCourseID = 0;
        try {
            rs = st.executeQuery("select ID from Course where Number = "+inCourse);
            while (rs.next()) {
                intCourseID = rs.getInt("ID");
            }
        } catch (SQLException ex) {
            Logger.getLogger(jpAddClass.class.getName()).log(Level.SEVERE, null, ex);
        }
        return intCourseID;
    }
    
// This gets the campus Id by passing it the campus name
    private int getCampusID(String inCampus){
        ResultSet rs;
        int intCampusID = 0;
        System.out.println(inCampus);
        try {
            rs = st.executeQuery("select ID from Campus where CampusName = '"+inCampus+"'");
            while (rs.next()) {
                intCampusID = rs.getInt("ID");
            }
        } catch (SQLException ex) {
            Logger.getLogger(jpAddClass.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("");
        }
        return intCampusID;
    }
    
// This is the class that sets all the local variables that will get inserted into the database. 
    private void jbAddClassFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddClassFinishActionPerformed
        setCourse(jcbCourse);
        setCampus(jcbCampus);
        setMeetingLocation(jtfMeetingLocation);
        setSection(jtfSection);
        setScheduleNumber(jtfScheduleNumber);
        setAngelID(jtfAngelID);
        setAngelTitle(jtfAngelTitle);
        setMondayStart(jcbMondayStart);
        setMondayEnd(jcbMondayEnd);
        setTuesdayStart(jcbTuesdayStart);
        setTuesdayEnd(jcbTuesdayEnd);
        setWednesdayStart(jcbWednesdayStart);
        setWednesdayEnd(jcbWednesdayEnd);
        setThursdayStart(jcbThursdayStart);
        setThursdayEnd(jcbThursdayEnd);
        setFridayStart(jcbFridayStart);
        setFridayEnd(jcbFridayEnd);
        setSaturdayStart(jcbSaturdayStart);
        setSaturdayEnd(jcbSaturdayEnd);
        setSundayStart(jcbSundayStart);
        setSundayEnd(jcbSundayEnd);
        
        InsertToTable(getCourseID(intCourse), getCampusID(strCampus), strMeetingLocation,intSection,intScheduleNumber,
                     strAngelID,strAngelTitle,strMondayStart,strMondayEnd,strTuesdayStart,strTuesdayEnd,strWednesdayStart,
                     strWednesdayEnd,strThursdayStart,strThursdayEnd,strFridayStart,strFridayEnd,strSaturdayStart,
                     strSaturdayEnd,strSundayStart,strSundayEnd,strNotes);
        this.getTopLevelAncestor().setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAddClassFinishActionPerformed

    private void InsertToTable(int inCourseID, int inCampusID, String inMeetingLocation, int inSection,
                               int inScheduleNumber, String inAngelID, String inAngelTitle, String inMondayStart,
                               String inMondayEnd, String inTuesdayStart, String inTuesdayEnd, String inWednesdayStart,
                               String inWednesdayEnd, String inThursdayStart, String inThursdayEnd, String inFridayStart,
                               String inFridayEnd, String inSaturdayStart, String inSaturdayEnd, String inSundayStart,
                               String inSundayEnd, String inNotes){
        try {
            String query = " INSERT INTO Class (FKCourse, FKCampus, MeetingLocation, Section, ScheduleNumber,"
                           + " ANGELID, ANGELTitle, tmMondayStart, tmMondayEnd, tmTuesdayStart, tmTuesdayEnd,"
                           + " tmWednesdayStart,tmWednesdayEnd, tmThursdayStart, tmFridayStart, tmFridayEnd, "
                           + "tmSaturdayStart, tmSaturdayEnd, tmSundayStart, tmSundayEnd, Notes, tmThursdayEnd)"
                           + " VALUES (?, ?, ?, ?, ?,?,?,?,?,?,?, ?, ?, ?, ?,?,?,?,?,?,?,?)";//22
             pst = dbConnection.prepareStatement(query);
             pst.setInt(1, inCourseID);
             pst.setInt(2, inCampusID);
             pst.setString(3, inMeetingLocation);
             pst.setInt(4, inSection);
             pst.setInt(5, inScheduleNumber);
             pst.setString(6, inAngelID);
             pst.setString(7, inAngelTitle);
             pst.setString(8, inMondayStart);
             pst.setString(9, inMondayEnd);
             pst.setString(10, inTuesdayStart);
             pst.setString(11, inTuesdayEnd);
             pst.setString(12, inWednesdayStart);
             pst.setString(13, inWednesdayEnd);
             pst.setString(14, inThursdayStart);
             pst.setString(22, inThursdayEnd);
             pst.setString(15, inFridayStart);
             pst.setString(16, inFridayEnd);
             pst.setString(17, inSaturdayStart);
             pst.setString(18, inSaturdayEnd);
             pst.setString(19, inSundayStart);
             pst.setString(20, inSundayEnd);
             pst.setString(21, inNotes);
             pst.execute();
        } catch (SQLException ex) {
            Logger.getLogger(jpAddClass.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Failed");
        }
        
    }
    private void jchbMondayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jchbMondayStateChanged
        if(jchbMonday.isSelected()){
            jcbMondayStart.setEnabled(true);
            jcbMondayEnd.setEnabled(true);
        }
        else{
            jcbMondayStart.setEnabled(false);
            jcbMondayEnd.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jchbMondayStateChanged

    private void jchbTuesdayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jchbTuesdayStateChanged
        // TODO add your handling code here:
        if(jchbTuesday.isSelected()){
            jcbTuesdayStart.setEnabled(true);
            jcbTuesdayEnd.setEnabled(true);
        }
        else{
            jcbTuesdayStart.setEnabled(false);
            jcbTuesdayEnd.setEnabled(false);
        }
    }//GEN-LAST:event_jchbTuesdayStateChanged

    private void jchbSundayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jchbSundayStateChanged
        // TODO add your handling code here:
        if(jchbSunday.isSelected()){
            jcbSundayStart.setEnabled(true);
            jcbSundayEnd.setEnabled(true);
        }
        else{
            jcbSundayStart.setEnabled(false);
            jcbSundayEnd.setEnabled(false);
        }
    }//GEN-LAST:event_jchbSundayStateChanged

    private void jchbSaturdayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jchbSaturdayStateChanged
        // TODO add your handling code here:
        if(jchbSaturday.isSelected()){
            jcbSaturdayStart.setEnabled(true);
            jcbSaturdayEnd.setEnabled(true);
        }
        else{
            jcbSaturdayStart.setEnabled(false);
            jcbSaturdayEnd.setEnabled(false);
        }
    }//GEN-LAST:event_jchbSaturdayStateChanged

    private void jchbFridayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jchbFridayStateChanged
        // TODO add your handling code here:
        if(jchbFriday.isSelected()){
            jcbFridayStart.setEnabled(true);
            jcbFridayEnd.setEnabled(true);
        }
        else{
            jcbFridayStart.setEnabled(false);
            jcbFridayEnd.setEnabled(false);
        }
    }//GEN-LAST:event_jchbFridayStateChanged

    private void jchbThursdayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jchbThursdayStateChanged
        // TODO add your handling code here:
        if(jchbThursday.isSelected()){
            jcbThursdayStart.setEnabled(true);
            jcbThursdayEnd.setEnabled(true);
        }
        else{
            jcbThursdayStart.setEnabled(false);
            jcbThursdayEnd.setEnabled(false);
        }
    }//GEN-LAST:event_jchbThursdayStateChanged

    private void jchbWednesdayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jchbWednesdayStateChanged
        // TODO add your handling code here:
        if(jchbWednesday.isSelected()){
            jcbWednesdayStart.setEnabled(true);
            jcbWednesdayEnd.setEnabled(true);
        }
        else{
            jcbWednesdayStart.setEnabled(false);
            jcbWednesdayEnd.setEnabled(false);
        }
    }//GEN-LAST:event_jchbWednesdayStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAddClassFinish;
    private javax.swing.JComboBox jcbCampus;
    private javax.swing.JComboBox jcbCourse;
    private javax.swing.JComboBox jcbFridayEnd;
    private javax.swing.JComboBox jcbFridayStart;
    private javax.swing.JComboBox jcbMondayEnd;
    private javax.swing.JComboBox jcbMondayStart;
    private javax.swing.JComboBox jcbSaturdayEnd;
    private javax.swing.JComboBox jcbSaturdayStart;
    private javax.swing.JComboBox jcbSundayEnd;
    private javax.swing.JComboBox jcbSundayStart;
    private javax.swing.JComboBox jcbThursdayEnd;
    private javax.swing.JComboBox jcbThursdayStart;
    private javax.swing.JComboBox jcbTuesdayEnd;
    private javax.swing.JComboBox jcbTuesdayStart;
    private javax.swing.JComboBox jcbWednesdayEnd;
    private javax.swing.JComboBox jcbWednesdayStart;
    private javax.swing.JCheckBox jchbFriday;
    private javax.swing.JCheckBox jchbMonday;
    private javax.swing.JCheckBox jchbSaturday;
    private javax.swing.JCheckBox jchbSunday;
    private javax.swing.JCheckBox jchbThursday;
    private javax.swing.JCheckBox jchbTuesday;
    private javax.swing.JCheckBox jchbWednesday;
    private javax.swing.JLabel jlAngelID;
    private javax.swing.JLabel jlAngelTitle;
    private javax.swing.JLabel jlCampus;
    private javax.swing.JLabel jlCourse;
    private javax.swing.JLabel jlEndTime;
    private javax.swing.JLabel jlFridayTo;
    private javax.swing.JLabel jlMeetingDays;
    private javax.swing.JLabel jlMeetingLocation;
    private javax.swing.JLabel jlMondayTo;
    private javax.swing.JLabel jlNotes;
    private javax.swing.JLabel jlSaturdayTo;
    private javax.swing.JLabel jlScheduleNumber;
    private javax.swing.JLabel jlSection;
    private javax.swing.JLabel jlStartTime;
    private javax.swing.JLabel jlSundayTo;
    private javax.swing.JLabel jlThursdayTo;
    private javax.swing.JLabel jlTuesdayTo;
    private javax.swing.JLabel jlWednesdayTo;
    private javax.swing.JTextArea jtaNotes;
    private javax.swing.JTextField jtfAngelID;
    private javax.swing.JTextField jtfAngelTitle;
    private javax.swing.JTextField jtfMeetingLocation;
    private javax.swing.JTextField jtfScheduleNumber;
    private javax.swing.JTextField jtfSection;
    // End of variables declaration//GEN-END:variables
}
