/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IST261DesktopPaneDemo;

/**
 *
 * @author Nathan
 */
public class jpAddClass extends javax.swing.JPanel {

    /**
     * Creates new form jpAddClass
     */
    public jpAddClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlClassName = new javax.swing.JLabel();
        jtfClassName = new javax.swing.JTextField();
        jbAddClassFinish = new javax.swing.JButton();
        jlMeetingLocation = new javax.swing.JLabel();
        jtfMettingLocation = new javax.swing.JTextField();
        jlSection = new javax.swing.JLabel();
        jlScheduleNumber = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jlAngelID = new javax.swing.JLabel();

        jlClassName.setText("Class Name");

        jbAddClassFinish.setText("Finish");
        jbAddClassFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddClassFinishActionPerformed(evt);
            }
        });

        jlMeetingLocation.setText("Meeting Location");

        jlSection.setText("Section");

        jlScheduleNumber.setText("Schedule Number");

        jTextField1.setText("jTextField1");

        jlAngelID.setText("ANGEL ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlAngelID)
                    .addComponent(jlSection)
                    .addComponent(jlMeetingLocation)
                    .addComponent(jlClassName)
                    .addComponent(jlScheduleNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAddClassFinish)
                    .addComponent(jtfClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMettingLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlClassName)
                    .addComponent(jtfClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlMeetingLocation)
                    .addComponent(jtfMettingLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSection)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlScheduleNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlAngelID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jbAddClassFinish))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddClassFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddClassFinishActionPerformed
        this.getTopLevelAncestor().setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAddClassFinishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbAddClassFinish;
    private javax.swing.JLabel jlAngelID;
    private javax.swing.JLabel jlClassName;
    private javax.swing.JLabel jlMeetingLocation;
    private javax.swing.JLabel jlScheduleNumber;
    private javax.swing.JLabel jlSection;
    private javax.swing.JTextField jtfClassName;
    private javax.swing.JTextField jtfMettingLocation;
    // End of variables declaration//GEN-END:variables
}
