/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IST261DesktopPaneDemo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JCheckBox;

/**
 *
 * @author Nick
 */
public class jpAddAssignment extends javax.swing.JPanel {

    /**
     * Creates new form jpAssignment
     */
        private Connection dbConnection;
        public jpAddAssignment(Connection inConnection)
        {
            initComponents();
            dbConnection = inConnection;
        }
        private Statement st;
        private PreparedStatement pst;
         

    // vars that get passed to the database
    private String strAssignment = null;
    private String strDescription = null;
    private String strSpecification = null;
    private String strNotes = null;
    private String strGradeNotes = null;
    private int intPoints = 0;
    private String strAttendance = null;
    private String strGroup = null;
        
    
    //This sets the Course from the drop down on the screen
    private void setAssignment(JTextField injtfAssignment){
        String selected = injtfAssignment.getSelectedText();
        strAssignment = selected;
    }
    
    //This sets the Course from the drop down on the screen
    private void setMaxPoints(JTextField injtfMaxPoints){
        int selected = Integer.parseInt(injtfMaxPoints.getSelectedText());
        intPoints = selected;
    } //setMaxPoints
    
    
    //This sets the Course from the drop down on the screen
    private void setAttendance(JCheckBox jcbAttendance){
        if (jcbAttendance.isSelected()){
            strAttendance = "yes";
        }// if
        else{    
            strAttendance = "no";
        };// else   
    }// setAttendance
    
    
    //This sets the Course from the drop down on the screen
    private void setGroup(JCheckBox jcbGroup){
        if (jcbGroup.isSelected()){
            strGroup = "yes";
        }// if
        else{    
            strGroup = "no";
        };// else
        
    }
    
    
    // This sets the Assignment Name based on the User's input.
    private void setDescription(JTextArea injtaDescription){
        strAssignment = injtaDescription.getText();
    }// setDescription
    
    
    // This sets the Assignment Name based on the User's input.
    private void setSpecification(JTextArea injtaSpecification){
        strAssignment = injtaSpecification.getText();
    }// setSpecification
    
    
    // This sets the Assignment Name based on the User's input.
    private void setNotes(JTextArea injtaNotes){
        strAssignment = injtaNotes.getText();
    }// setNotes
    
    
    // This sets the Assignment Name based on the User's input.
    private void setGradeNotes(JTextArea injtaGradeNotes){
        strAssignment = injtaGradeNotes.getText();
    }//setGradeNotes
    
    // this inserts all the data into the class table in the DB
    private void InsertToTable(String inAssignment, String inDescription, String inSpecification, int inPoints, String inNotes, String inGradeNotes, String inAttendance, String inGroup){
        try {
            String query = " INSERT INTO Assignments (ShortName, Description, Specification, MaximumPoints, Notes,"
                           + " GradingNotes, AttendanceRequired, GroupAssignment"
                           + " VALUES (?, ?, ?, ?, ?, ?, ?, ?)";//8
             pst = dbConnection.prepareStatement(query);
             pst.setString(1, inAssignment);
             pst.setString(2, inDescription);
             pst.setString(3, inSpecification);
             pst.setInt(4, inPoints);
             pst.setString(5, inNotes);
             pst.setString(6, inGradeNotes);
             pst.setString(7, inAttendance);
             pst.setString(8, inGroup);
             pst.execute();
        } catch (SQLException ex) {
            Logger.getLogger(jpAddClass.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Failed");
        }
        
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jlAssignmentName = new javax.swing.JLabel();
        jtfAssignmentName = new javax.swing.JTextField();
        jchbGroupAssignment = new javax.swing.JCheckBox();
        jbAddAssignmentFinish = new javax.swing.JButton();
        jlMaxPoints = new javax.swing.JLabel();
        jtfPoints = new javax.swing.JTextField();
        jlDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescription = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaSpecification = new javax.swing.JTextArea();
        jlSpecification = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtaNotes = new javax.swing.JTextArea();
        jlNotes = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtaGradingNotes = new javax.swing.JTextArea();
        jlGradingNotes = new javax.swing.JLabel();
        jchAttendanceRequired = new javax.swing.JCheckBox();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jlAssignmentName.setText("Name");

        jchbGroupAssignment.setText("Group Assignment");
        jchbGroupAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchbGroupAssignmentActionPerformed(evt);
            }
        });

        jbAddAssignmentFinish.setText("Finsih");
        jbAddAssignmentFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddAssignmentFinishActionPerformed(evt);
            }
        });

        jlMaxPoints.setText("Maximum Points");

        jlDescription.setText("Description");

        jtaDescription.setColumns(20);
        jtaDescription.setRows(5);
        jScrollPane1.setViewportView(jtaDescription);

        jtaSpecification.setColumns(20);
        jtaSpecification.setRows(5);
        jScrollPane3.setViewportView(jtaSpecification);

        jlSpecification.setText("Specification");

        jtaNotes.setColumns(20);
        jtaNotes.setRows(5);
        jScrollPane4.setViewportView(jtaNotes);

        jlNotes.setText("Notes");

        jtaGradingNotes.setColumns(20);
        jtaGradingNotes.setRows(5);
        jScrollPane5.setViewportView(jtaGradingNotes);

        jlGradingNotes.setText("Grading Notes");

        jchAttendanceRequired.setText("Attendance Required");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jlNotes)
                        .addGap(152, 152, 152)
                        .addComponent(jlGradingNotes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jchbGroupAssignment)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane4)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchAttendanceRequired, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jlDescription)
                        .addGap(145, 145, 145)
                        .addComponent(jlSpecification))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jlAssignmentName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlMaxPoints)
                            .addComponent(jtfPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jtfAssignmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jbAddAssignmentFinish)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlAssignmentName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfAssignmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlMaxPoints)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlDescription)
                    .addComponent(jlSpecification))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNotes)
                    .addComponent(jlGradingNotes))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchbGroupAssignment)
                    .addComponent(jchAttendanceRequired))
                .addGap(18, 18, 18)
                .addComponent(jbAddAssignmentFinish)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddAssignmentFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddAssignmentFinishActionPerformed
        this.getTopLevelAncestor().setVisible(false);
            //setting the Course number

        setAssignment(jtfAssignmentName);
        setDescription(jtaDescription);
        setMaxPoints(jtfPoints);
        setSpecification(jtaSpecification);
        setNotes(jtaNotes);
        setGradeNotes(jtaGradingNotes);
        setAttendance(jchAttendanceRequired);
        setGroup(jchbGroupAssignment);
        
        
        InsertToTable(strAssignment, strDescription, strSpecification, intPoints, strNotes, strGradeNotes, strAttendance, strGroup);
    }//GEN-LAST:event_jbAddAssignmentFinishActionPerformed

    private void jchbGroupAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchbGroupAssignmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchbGroupAssignmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbAddAssignmentFinish;
    private javax.swing.JCheckBox jchAttendanceRequired;
    private javax.swing.JCheckBox jchbGroupAssignment;
    private javax.swing.JLabel jlAssignmentName;
    private javax.swing.JLabel jlDescription;
    private javax.swing.JLabel jlGradingNotes;
    private javax.swing.JLabel jlMaxPoints;
    private javax.swing.JLabel jlNotes;
    private javax.swing.JLabel jlSpecification;
    private javax.swing.JTextArea jtaDescription;
    private javax.swing.JTextArea jtaGradingNotes;
    private javax.swing.JTextArea jtaNotes;
    private javax.swing.JTextArea jtaSpecification;
    private javax.swing.JTextField jtfAssignmentName;
    private javax.swing.JTextField jtfPoints;
    // End of variables declaration//GEN-END:variables
}
