/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IST261DesktopPaneDemo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JCheckBox;
import javax.swing.JSpinner;

/**
 *
 * @author Nick
 */
public class jpAddAssignment extends javax.swing.JPanel {

    /**
     * Creates new form jpAssignment
     */
    
    private Connection dbConnection;
    public jpAddAssignment(Connection inConnection){
        initComponents();
        dbConnection = inConnection;
    }// jpAddAssignment
        
    //Statement values    
    private Statement st;
    private PreparedStatement pst;
         

    // vars that get passed to the database
    private String strAssignment = null;
    private String strDescription = null;
    private String strSpecification = null;
    private String strNotes = null;
    private String strGradeNotes = null;
    private int intPoints = 0;
    private boolean blAttendance = false;
    private boolean blGroup = false;
        
    
    //This sets the Assignment name from user input.
    private void setAssignment(JTextField injtfAssignment){
        String selected = injtfAssignment.getText();
        strAssignment = selected;
    }// setAssignment
    
    //This sets the Point value for the assignment from user input.
    private void setMaxPoints(JSpinner injsPoints){
        int selected = (Integer)injsPoints.getValue();
        intPoints = selected;
    } //setMaxPoints
    
    
    //This sets attendance required boolean from checkbox.
    private void setAttendance(JCheckBox jcbAttendance){
        if (jcbAttendance.isSelected()){
            blAttendance = true;
        }// if
    }// setAttendance
    
    
    //This sets group grade boolean from checkbox.
    private void setGroup(JCheckBox jcbGroup){
        if (jcbGroup.isSelected()){
            blGroup = true;
        }// if       
    }// setGroup
    
    
    // This sets description area based on user input.
    private void setDescription(JTextArea injtaDescription){
        strDescription = injtaDescription.getText();
    }// setDescription
    
    
    // This sets the specification area based on user input.
    private void setSpecification(JTextArea injtaSpecification){
        strSpecification = injtaSpecification.getText();
    }// setSpecification
    
    
    // This sets the notes area based on user input.
    private void setNotes(JTextArea injtaNotes){
        strNotes = injtaNotes.getText();
    }// setNotes
    
    
    // This sets the gradenotes area based on user input.
    private void setGradeNotes(JTextArea injtaGradeNotes){
        strGradeNotes = injtaGradeNotes.getText();
    }//setGradeNotes
    
    // This inserts all the data into the Assignments table in the DB
    private void InsertToTable(String inAssignment, String inDescription, String inSpecification, int inPoints, String inNotes, String inGradeNotes, boolean inAttendance, boolean inGroup){
        try {
            String query = "INSERT INTO Assignments (ShortName, Description, Specification, MaximumPoints, Notes, GradingNotes, \n" +
                            " AttendanceRequired, GroupAssignment)\n" +
                            " VALUES (?, ?, ?, ?, ?, ?, ?, ?)";//8
             pst = dbConnection.prepareStatement(query);
             pst.setString(1, inAssignment);
             pst.setString(2, inDescription);
             pst.setString(3, inSpecification);
             pst.setInt(4, inPoints);
             pst.setString(5, inNotes);
             pst.setString(6, inGradeNotes);
             pst.setBoolean(7, inAttendance);
             pst.setBoolean(8, inGroup);
             pst.execute();
        } catch (SQLException ex) {
            Logger.getLogger(jpAddClass.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Failed");
        }// try/catch
        
    }// insertToTable
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jlAssignmentName = new javax.swing.JLabel();
        jtfAssignmentName = new javax.swing.JTextField();
        jchbGroupAssignment = new javax.swing.JCheckBox();
        jbAddAssignmentFinish = new javax.swing.JButton();
        jlMaxPoints = new javax.swing.JLabel();
        jlDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescription = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaSpecification = new javax.swing.JTextArea();
        jlSpecification = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtaNotes = new javax.swing.JTextArea();
        jlNotes = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtaGradingNotes = new javax.swing.JTextArea();
        jlGradingNotes = new javax.swing.JLabel();
        jchAttendanceRequired = new javax.swing.JCheckBox();
        jsMaxPoints = new javax.swing.JSpinner();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setMinimumSize(new java.awt.Dimension(432, 508));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlAssignmentName.setText("Assignment Name");
        add(jlAssignmentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 20));
        add(jtfAssignmentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 239, 30));

        jchbGroupAssignment.setText("Group Assignment");
        jchbGroupAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchbGroupAssignmentActionPerformed(evt);
            }
        });
        add(jchbGroupAssignment, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jbAddAssignmentFinish.setText("Finish");
        jbAddAssignmentFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddAssignmentFinishActionPerformed(evt);
            }
        });
        add(jbAddAssignmentFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        jlMaxPoints.setText("Maximum Points");
        add(jlMaxPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, 20));

        jlDescription.setText("Description");
        add(jlDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        jtaDescription.setColumns(20);
        jtaDescription.setRows(5);
        jScrollPane1.setViewportView(jtaDescription);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 240, 120));

        jtaSpecification.setColumns(20);
        jtaSpecification.setRows(5);
        jScrollPane3.setViewportView(jtaSpecification);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 240, 120));

        jlSpecification.setText("Specification");
        add(jlSpecification, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, 30));

        jtaNotes.setColumns(20);
        jtaNotes.setRows(5);
        jScrollPane4.setViewportView(jtaNotes);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, 120));

        jlNotes.setText("Notes");
        add(jlNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));

        jtaGradingNotes.setColumns(20);
        jtaGradingNotes.setRows(5);
        jScrollPane5.setViewportView(jtaGradingNotes);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 240, 120));

        jlGradingNotes.setText("Grading Notes");
        add(jlGradingNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, 30));

        jchAttendanceRequired.setText("Attendance Required");
        add(jchAttendanceRequired, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));
        add(jsMaxPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 64, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddAssignmentFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddAssignmentFinishActionPerformed
        this.getTopLevelAncestor().setVisible(false);
            //setting the Course number

        setAssignment(jtfAssignmentName);
        setDescription(jtaDescription);
        setMaxPoints(jsMaxPoints);
        setSpecification(jtaSpecification);
        setNotes(jtaNotes);
        setGradeNotes(jtaGradingNotes);
        setAttendance(jchAttendanceRequired);
        setGroup(jchbGroupAssignment);
        
        
        InsertToTable(strAssignment, strDescription, strSpecification, intPoints, strNotes, strGradeNotes, blAttendance, blGroup);
    }//GEN-LAST:event_jbAddAssignmentFinishActionPerformed

    private void jchbGroupAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchbGroupAssignmentActionPerformed
        
    }//GEN-LAST:event_jchbGroupAssignmentActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbAddAssignmentFinish;
    private javax.swing.JCheckBox jchAttendanceRequired;
    private javax.swing.JCheckBox jchbGroupAssignment;
    private javax.swing.JLabel jlAssignmentName;
    private javax.swing.JLabel jlDescription;
    private javax.swing.JLabel jlGradingNotes;
    private javax.swing.JLabel jlMaxPoints;
    private javax.swing.JLabel jlNotes;
    private javax.swing.JLabel jlSpecification;
    private javax.swing.JSpinner jsMaxPoints;
    private javax.swing.JTextArea jtaDescription;
    private javax.swing.JTextArea jtaGradingNotes;
    private javax.swing.JTextArea jtaNotes;
    private javax.swing.JTextArea jtaSpecification;
    private javax.swing.JTextField jtfAssignmentName;
    // End of variables declaration//GEN-END:variables
}
