/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IST261DesktopPaneDemo;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Nathan
 */
public class jpClass extends javax.swing.JPanel {

    /**
     * Creates new form jpClass
     */
    
    private Statement st;
    
    private Connection dbConnection;
    
    public jpClass() {
        initComponents();
    }
    
    public jpClass(Connection inConnection){
        initComponents();
        setdbConnection(inConnection);;
        setjcbCourse();
        
    }
    // This sets the local datbase connection
    private void setdbConnection(Connection inConnection){
        dbConnection = inConnection;
        try {             
            st = dbConnection.createStatement();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }
    // fill the course drop down box
    private void setjcbCourse(){
        jcbCourse.removeAllItems();
        jcbCourse.addItem("Select Course");
 
        try {
             
            ResultSet rs = st.executeQuery("select Number from Course order by Number asc");

            while (rs.next()) {
                jcbCourse.addItem(//rs.getString("IST") + " " + 
                        rs.getString("Number"));
            }
            
        } catch (SQLException sqle) {
            System.out.println(sqle);
        }
    }
    // fills the class drop down box
    private void setjcbClass(){
        jcbClass.removeAllItems();
        jcbClass.addItem("Select Class");
 
        try {
            int intSelectedCourse = Integer.parseInt(jcbCourse.getSelectedItem()+"");
            int intSelectedCourseID = 0;
            ResultSet rs = st.executeQuery("select ID from Course where Number  = "+intSelectedCourse);
            while (rs.next()) {
                intSelectedCourseID = rs.getInt("ID");
            }
            st.executeQuery("select Section from Class where FKCourse ="+intSelectedCourseID);
            while (rs.next()) {
                jcbClass.addItem(//rs.getString("IST") + " " + 
                        rs.getString("Section"));
            }
        } catch (SQLException sqle) {
            System.out.println(sqle);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbClass = new javax.swing.JComboBox();
        jbAddClass = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpClassOverviewTab = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpClassStudentsTab = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfPhoneNumber = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jtfStudentID = new javax.swing.JTextField();
        jtfLastName = new javax.swing.JTextField();
        jtfFirstName = new javax.swing.JTextField();
        jbImportStudents = new javax.swing.JButton();
        jbSave = new javax.swing.JButton();
        jbDelete = new javax.swing.JButton();
        jpClassGradesTab = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtAssignments = new javax.swing.JTable();
        jlAssignments = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jbSaveGrades = new javax.swing.JButton();
        jpClassAssignmentTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtIndividualAssignments = new javax.swing.JTable();
        jlGroupAssignments = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtGroupAssignments = new javax.swing.JTable();
        jbNewAssignment = new javax.swing.JButton();
        jbDeleteAssignment = new javax.swing.JButton();
        jbRefreshAssignment = new javax.swing.JButton();
        jbChangeAssignment = new javax.swing.JButton();
        jcbCourse = new javax.swing.JComboBox();

        jcbClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Open Class", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbClass.setEnabled(false);

        jbAddClass.setText("Add Class");
        jbAddClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddClassActionPerformed(evt);
            }
        });

        jLabel6.setText("Calendar MAYBE");

        javax.swing.GroupLayout jpClassOverviewTabLayout = new javax.swing.GroupLayout(jpClassOverviewTab);
        jpClassOverviewTab.setLayout(jpClassOverviewTabLayout);
        jpClassOverviewTabLayout.setHorizontalGroup(
            jpClassOverviewTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClassOverviewTabLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel6)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jpClassOverviewTabLayout.setVerticalGroup(
            jpClassOverviewTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClassOverviewTabLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addContainerGap(559, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Overview", jpClassOverviewTab);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Nathan", "Faust", "NRF5061"},
                {"Nick", "Youndt", "NZY5033"},
                {"Derek", "Goodman", "DMG5572"},
                {null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "ID"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        jLabel3.setText("First Name");

        jLabel4.setText("Last Name");

        jLabel8.setText("Student ID");

        jLabel9.setText("Email");

        jLabel10.setText("Phone Number");

        jtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmailActionPerformed(evt);
            }
        });

        jtfStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfStudentIDActionPerformed(evt);
            }
        });

        jtfFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFirstNameActionPerformed(evt);
            }
        });

        jbImportStudents.setText("Import");

        jbSave.setText("Save");

        jbDelete.setText("Delete");

        javax.swing.GroupLayout jpClassStudentsTabLayout = new javax.swing.GroupLayout(jpClassStudentsTab);
        jpClassStudentsTab.setLayout(jpClassStudentsTabLayout);
        jpClassStudentsTabLayout.setHorizontalGroup(
            jpClassStudentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClassStudentsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClassStudentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jpClassStudentsTabLayout.createSequentialGroup()
                        .addGroup(jpClassStudentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpClassStudentsTabLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(46, 46, 46))
                            .addGroup(jpClassStudentsTabLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jpClassStudentsTabLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(20, 20, 20))
                            .addGroup(jpClassStudentsTabLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(19, 19, 19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpClassStudentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpClassStudentsTabLayout.createSequentialGroup()
                                .addGroup(jpClassStudentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfFirstName)
                                    .addComponent(jtfLastName)
                                    .addComponent(jtfStudentID)
                                    .addComponent(jtfEmail)
                                    .addComponent(jtfPhoneNumber))
                                .addGap(97, 97, 97))
                            .addGroup(jpClassStudentsTabLayout.createSequentialGroup()
                                .addComponent(jbImportStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(88, 88, 88))))
        );
        jpClassStudentsTabLayout.setVerticalGroup(
            jpClassStudentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClassStudentsTabLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpClassStudentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClassStudentsTabLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpClassStudentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClassStudentsTabLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpClassStudentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClassStudentsTabLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpClassStudentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClassStudentsTabLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpClassStudentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClassStudentsTabLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpClassStudentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbImportStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(281, 281, 281))
        );

        jTabbedPane1.addTab("Students", jpClassStudentsTab);

        jtAssignments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Team Charter", "1/15/16", "5", null},
                {"Proposal", "1/25/16", "10", "yes"},
                {"UID 1", "1/15/16", "2", "no"},
                {"Networking", "1/25/16", "10", "no"},
                {"UID 2", "2/12/16", "2", "no"},
                {"System Users Tasks", "2/12/16", "10", "yes"}
            },
            new String [] {
                "Assignment", "Due Date", "Points", "Group"
            }
        ));
        jScrollPane3.setViewportView(jtAssignments);

        jlAssignments.setText("Assignments:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Team 1", "5", "10", null},
                {"Team 2", "10", "10", null},
                {"", null, null, null}
            },
            new String [] {
                "Name", "Points Earned", "Points Possible", "Comment"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jLabel1.setText("Assign To:");

        jbSaveGrades.setText("Save");

        javax.swing.GroupLayout jpClassGradesTabLayout = new javax.swing.GroupLayout(jpClassGradesTab);
        jpClassGradesTab.setLayout(jpClassGradesTabLayout);
        jpClassGradesTabLayout.setHorizontalGroup(
            jpClassGradesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClassGradesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpClassGradesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClassGradesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlAssignments)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jbSaveGrades))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpClassGradesTabLayout.setVerticalGroup(
            jpClassGradesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClassGradesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlAssignments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSaveGrades)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Grades", jpClassGradesTab);

        jtIndividualAssignments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"UID 1", "1/15/16", "Get Detail", "2"},
                {"UID 2", "1/25/16", "Get Detail", "2"},
                {"Networking", "2/12/16", "Get Detail", "10"},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Due Date", "Description", "Points"
            }
        ));
        jScrollPane1.setViewportView(jtIndividualAssignments);

        jlGroupAssignments.setText("Group Assignments:");

        jLabel7.setText("Individual Assignments:");

        jtGroupAssignments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Team Charter", "1/15/16", "Get Detail", "5"},
                {"Proposal", "1/25/16", "Get Detail", "10"},
                {"System Users Tasks", "2/12/16", "Get Detail", "10"},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Due Date", "Description", "Points"
            }
        ));
        jScrollPane2.setViewportView(jtGroupAssignments);

        jbNewAssignment.setText("New");
        jbNewAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewAssignmentActionPerformed(evt);
            }
        });

        jbDeleteAssignment.setText("Delete");

        jbRefreshAssignment.setText("Refresh");

        jbChangeAssignment.setText("Change");

        javax.swing.GroupLayout jpClassAssignmentTabLayout = new javax.swing.GroupLayout(jpClassAssignmentTab);
        jpClassAssignmentTab.setLayout(jpClassAssignmentTabLayout);
        jpClassAssignmentTabLayout.setHorizontalGroup(
            jpClassAssignmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClassAssignmentTabLayout.createSequentialGroup()
                .addGroup(jpClassAssignmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpClassAssignmentTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlGroupAssignments))
                    .addGroup(jpClassAssignmentTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jpClassAssignmentTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpClassAssignmentTabLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jbNewAssignment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDeleteAssignment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRefreshAssignment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbChangeAssignment))
                    .addGroup(jpClassAssignmentTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpClassAssignmentTabLayout.setVerticalGroup(
            jpClassAssignmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClassAssignmentTabLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jlGroupAssignments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpClassAssignmentTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNewAssignment)
                    .addComponent(jbDeleteAssignment)
                    .addComponent(jbRefreshAssignment)
                    .addComponent(jbChangeAssignment))
                .addContainerGap(319, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Assignemnts", jpClassAssignmentTab);

        jcbCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Open Course", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbCourse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCourseItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAddClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbClass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAddClass)
                    .addComponent(jcbClass)
                    .addComponent(jcbCourse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbAddClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddClassActionPerformed
        JPanel AddClass = new jpAddClass(dbConnection);
        AddClass.setName("Add Class");
        CreateFrame(AddClass);        // TODO add your handling code here:
    }//GEN-LAST:event_jbAddClassActionPerformed

    private void jbNewAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewAssignmentActionPerformed
//        JPanel SelectAssignment = new jpSelectAssignment();
//        SelectAssignment.setName("Select Assignment");
//        CreateFrame(SelectAssignment);         
//        // TODO add your handling code here:
    }//GEN-LAST:event_jbNewAssignmentActionPerformed

    private void jtfStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfStudentIDActionPerformed

    private void jtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEmailActionPerformed

    private void jtfFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFirstNameActionPerformed

    private void jcbCourseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCourseItemStateChanged
        if(jcbCourse.getSelectedIndex()>0){
            jcbClass.setEnabled(true);
            setjcbClass();
        }
        else{
            jcbClass.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCourseItemStateChanged
  private void CreateFrame(JPanel inPanel) {
                //  intWindowCounter++;
      JDialog jd = new JDialog();
      jd.add(inPanel);
      jd.pack();
      jd.setModal(true);
      jd.setVisible(true);
  }//CreateFrame

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbAddClass;
    private javax.swing.JButton jbChangeAssignment;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbDeleteAssignment;
    private javax.swing.JButton jbImportStudents;
    private javax.swing.JButton jbNewAssignment;
    private javax.swing.JButton jbRefreshAssignment;
    private javax.swing.JButton jbSave;
    private javax.swing.JButton jbSaveGrades;
    private javax.swing.JComboBox jcbClass;
    private javax.swing.JComboBox jcbCourse;
    private javax.swing.JLabel jlAssignments;
    private javax.swing.JLabel jlGroupAssignments;
    private javax.swing.JPanel jpClassAssignmentTab;
    private javax.swing.JPanel jpClassGradesTab;
    private javax.swing.JPanel jpClassOverviewTab;
    private javax.swing.JPanel jpClassStudentsTab;
    private javax.swing.JTable jtAssignments;
    private javax.swing.JTable jtGroupAssignments;
    private javax.swing.JTable jtIndividualAssignments;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfFirstName;
    private javax.swing.JTextField jtfLastName;
    private javax.swing.JTextField jtfPhoneNumber;
    private javax.swing.JTextField jtfStudentID;
    // End of variables declaration//GEN-END:variables

}
