/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IST261DesktopPaneDemo;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author whb108
 */
public class jpSQLiteDBInfo extends javax.swing.JPanel {

    /**
     * Creates new form jpSQLiteDBInfo
     */
    public jpSQLiteDBInfo(Connection inConnection) 
    {
        try {
            DatabaseMetaData dbmdInfo = inConnection.getMetaData();
            if (dbmdInfo.getDatabaseProductName().equals("SQLite") == false)
            {
                JOptionPane.showMessageDialog(this,
                        "The Connection is not a SQLite database!",
                        "Not a SQLite DB", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else
            {
               initComponents();
jtfDBProductName.setText(dbmdInfo.getDatabaseProductName());
jtfDBProductVersion.setText(dbmdInfo.getDatabaseProductVersion());
jtfDBMajorVersion.setText(Integer.toString(dbmdInfo.getDatabaseMajorVersion()));
jtfDBMinorVersion.setText(Integer.toString(dbmdInfo.getDatabaseMinorVersion()));
// dbmdInfo.getDriverName()                            
// dbmdInfo.getDriverVersion()               
              
            }
        } catch (SQLException ex) {
            Logger.getLogger(jpSQLiteDBInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfDBProductName = new javax.swing.JTextField();
        jlProductName = new javax.swing.JLabel();
        jtfDBProductVersion = new javax.swing.JTextField();
        jlProductVersion = new javax.swing.JLabel();
        jtfDBMajorVersion = new javax.swing.JTextField();
        jlDBMajorVersion = new javax.swing.JLabel();
        jtfDBMinorVersion = new javax.swing.JTextField();
        jlDBMinorVersion = new javax.swing.JLabel();

        jtfDBProductName.setEditable(false);

        jlProductName.setLabelFor(jtfDBProductName);
        jlProductName.setText("Product Name");

        jtfDBProductVersion.setEditable(false);
        jtfDBProductVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDBProductVersionActionPerformed(evt);
            }
        });

        jlProductVersion.setLabelFor(jtfDBProductVersion);
        jlProductVersion.setText("Product Version");

        jtfDBMajorVersion.setEditable(false);
        jtfDBMajorVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDBMajorVersionActionPerformed(evt);
            }
        });

        jlDBMajorVersion.setText("DB Major Version");

        jtfDBMinorVersion.setEditable(false);
        jtfDBMinorVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDBMinorVersionActionPerformed(evt);
            }
        });

        jlDBMinorVersion.setLabelFor(jtfDBMinorVersion);
        jlDBMinorVersion.setText("DB Major Version");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlProductName)
                    .addComponent(jlProductVersion)
                    .addComponent(jlDBMajorVersion)
                    .addComponent(jlDBMinorVersion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfDBMajorVersion)
                    .addComponent(jtfDBProductVersion)
                    .addComponent(jtfDBProductName)
                    .addComponent(jtfDBMinorVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDBProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlProductName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDBProductVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlProductVersion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDBMajorVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDBMajorVersion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDBMinorVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDBMinorVersion))
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDBProductVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDBProductVersionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDBProductVersionActionPerformed

    private void jtfDBMajorVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDBMajorVersionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDBMajorVersionActionPerformed

    private void jtfDBMinorVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDBMinorVersionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDBMinorVersionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlDBMajorVersion;
    private javax.swing.JLabel jlDBMinorVersion;
    private javax.swing.JLabel jlProductName;
    private javax.swing.JLabel jlProductVersion;
    private javax.swing.JTextField jtfDBMajorVersion;
    private javax.swing.JTextField jtfDBMinorVersion;
    private javax.swing.JTextField jtfDBProductName;
    private javax.swing.JTextField jtfDBProductVersion;
    // End of variables declaration//GEN-END:variables
}
