/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.psu.berksist.CourseEZ;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Deathx, jss5783
 * 
 *  ******************* MODIFICATION LOG *****************************************
 *  2017 April 19   -   Basic file-picking functionality added.
 *                      Continued roughing in code (not sure how data and reports are being generated yet). -JSS5783
 * 
 *  2017 April 17   -   Started laying the foundation for report generation, including a GUI makeover. -JSS5783
 */
public class jfReport extends javax.swing.JFrame
{
    private static String strFilepath = new String(AppConstants.ROOT_FOLDER);   //TODO: replace with dedicated reports folder; currently pointing to /resources
    private static String strFilename = new String("NewReport.docx");           //TODO: Replace with better default report name; maybe split into filename and file extension variables?
    
    /**
     * Creates new form ReportFrame
     */
    public jfReport()
    {
        initComponents();
        
        txtfFilepath.setText(strFilepath);
        txtfFilename.setText(strFilename);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFilepath = new javax.swing.JButton();
        btnGenerateReport = new javax.swing.JButton();
        txtfFilepath = new javax.swing.JTextField();
        txtfFilename = new javax.swing.JTextField();
        btnFilename = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generate Report");

        btnFilepath.setText("Change Filepath");
        btnFilepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilepathActionPerformed(evt);
            }
        });

        btnGenerateReport.setText("Generate Report");
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });

        btnFilename.setText("Change Filename");
        btnFilename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilenameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfFilepath, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(txtfFilename))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFilename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFilepath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerateReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilepath))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilename))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnGenerateReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Pick a new filepath to save reports in. (Doesn't pick files themselves, unless pointing at a folder to save in.) If invalid, changes aren't saved.
     * @param evt 
     */
    private void btnFilepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilepathActionPerformed
        try
        {
            JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int intFileChooserReturnValue = fc.showOpenDialog(this);
            
            if (intFileChooserReturnValue == JFileChooser.APPROVE_OPTION)   //if filepath is valid
            {
                //File file = fc.getSelectedFile();
                File fileFilepath = fc.getCurrentDirectory();
                strFilepath = fileFilepath.getPath();
                txtfFilepath.setText(strFilepath);
            }
            else if (intFileChooserReturnValue == JFileChooser.ERROR_OPTION)
            {
                throw new Exception();  //not sure what pops error, but if one can choose an invalid filepath, then maybe pop an error dialog about invalid target?
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFilepathActionPerformed

    /**
     * Generates a report.
     * TODO: report data gets passed in how and where?
     * @param evt 
     */
    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        /*
        TODO
        try
        {
            //check if filepath is valid
            //check if filename is valid
            //check if data getting passed is valid here, I guess
            //if file already exists
            //  then ask if user wants to overwrite the preexisting file (default selection is "no")
            //      if true
            //          if file is (over)writeable ((and location can be written to))
            //              try to overwrite preexisting file with passed-in data
            //                  pop dialog stating "Report generated!"
            //              catch any errors for whatever reason with an error dialog
            //          otherwise
            //              pop error dialog stating "Report generation failed!", that the file cannot be overwritten or location cannot be written to or whatever, and with error log
            //otherwise
            //  if location can be written to
            //      try to write to file with passed-in data
            //          pop dialog stating "Report generated!"
            //      catch any errors for whatever reason with an error dialog with error log
            //  otherwise
            //      pop error dialog stating "Report generation failed!", that the file cannot be overwritten or location cannot be written to or whatever, and with error log
            
            //TODO: Possibly if a lot of reports get generated in short order, instead of dialog boxes, just pop colored labels to reduce clicking
            //Also a bunch of radio buttons for filetype(s). i.e., PDF, DOCX, or both.
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        */
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    /**
     * Pick a new filename.
     * TODO: can pick from file picker dialog, I guess - just harvest for preexisting name that is a DOCX or PDF or whatever
     * @param evt 
     */
    private void btnFilenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilenameActionPerformed
        /*
        TODO
        rather than pulling from wherever JFileChooser decides to start from,
        check if current string in textbook is valid (since it can be typed in, not just FileChooser picked)
        if valid, start there
        otherwise, start from default location
        should also be able to enter a new one in JFileChooser for future generation,
        just as FileChoosers in other programs allow one to "reserve" a namespace without an actual preexisting file
        */
                try
        {
            JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
//            fc.setFileFilter(new FileFilter()
//                {
//                    public String getDescription()
//                    {
//                        return "PDF (*.pdf)";
//                    }
//                    
//                    public boolean accept(File f)
//                    {
//                        if (f.isDirectory() )
//                        {
//                            return true;
//                        }
//                        else
//                        {
//                            String filename = f.getName().toLowerCase();
//                            return filename.endsWith(".pdf");
//                        }
//                    }
//                });
            fc.addChoosableFileFilter(new FileNameExtensionFilter("DOCX (*.docx)", "docx"));
            fc.addChoosableFileFilter(new FileNameExtensionFilter("PDF (*.pdf)", "pdf"));
            fc.setAcceptAllFileFilterUsed(false);
            int intFileChooserReturnValue = fc.showOpenDialog(this);
            
            if (intFileChooserReturnValue == JFileChooser.APPROVE_OPTION)   //if filepath is valid
            {
                File fileFilename = fc.getSelectedFile();
                strFilename = fileFilename.getName();
                txtfFilename.setText(strFilename);
            }
            else if (intFileChooserReturnValue == JFileChooser.ERROR_OPTION)
            {
                throw new Exception();  //not sure what pops error, but if one can choose an invalid filepath, then maybe pop an error dialog about invalid target?
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFilenameActionPerformed

//    for testing/debugging in isolation
//    /**
//     * @param args the command line arguments
//     */
//        public static void main(String[] args) {
//            
//        jfReport test = new jfReport();
//        test.setVisible(true);
//        
//
//        } //main
        
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportFrame().setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilename;
    private javax.swing.JButton btnFilepath;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JTextField txtfFilename;
    private javax.swing.JTextField txtfFilepath;
    // End of variables declaration//GEN-END:variables
}
