/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.psu.berksist.CourseEZ;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Deathx, jss5783
 * 
 *  ******************* MODIFICATION LOG *****************************************
 *  2017 April 20   -   WIP: GUI overhaul continued.
 *                          GUI-side dummy data complete.
 *                      Filename chooser can now choose nonexistent files in preparation for saving.
 *                      File choosers now start in the Resources folder instead of the user's root directory.
 *                      BUGFIX: Filepaths are now selected properly. -JSS5783
 *  2017 April 20   -   WIP: GUI overhaul. -JSS5783
 *  2017 April 19   -   Basic file-picking functionality added.
 *                      Continued roughing in code (not sure how data and reports are being generated yet). -JSS5783
 * 
 *  2017 April 17   -   Started laying the foundation for report generation, including a GUI makeover. -JSS5783
 */
public class jfReport extends javax.swing.JFrame
{
    private static String strFilepath = new String(AppConstants.ROOT_FOLDER);   //TODO: replace with dedicated reports folder; currently pointing to /resources
    private static String strFilename = new String("NewReport");           //TODO: Replace with better default report name; maybe split into filename and file extension variables?
    
    /**
     * Creates new form ReportFrame
     */
    public jfReport()
    {
        initComponents();
        
        txtfFilepath.setText(strFilepath);
        txtfFilename.setText(strFilename);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpProfile = new javax.swing.JPanel();
        btnNewProfile = new javax.swing.JButton();
        btnLoadProfile = new javax.swing.JButton();
        btnDeleteProfile = new javax.swing.JButton();
        btnSaveProfile = new javax.swing.JButton();
        scpListProfile = new javax.swing.JScrollPane();
        listProfile = new javax.swing.JList<>();
        jpClass = new javax.swing.JPanel();
        cmbDepartment = new javax.swing.JComboBox<>();
        cmbCourse = new javax.swing.JComboBox<>();
        cmbSection = new javax.swing.JComboBox<>();
        lblDepartment = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        lblSection = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpTemplate = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTemplateDefaultComponents = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listTemplateComponents = new javax.swing.JList<>();
        btnTemplateAddComponentToTemplate = new javax.swing.JButton();
        btnTemplateRemoveComponentFromTemplate = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableTemplateTableContents = new javax.swing.JTable();
        btnAddComponentToTable = new javax.swing.JButton();
        btnRemoveComponentFromTable = new javax.swing.JButton();
        jpTemplateTableSize = new javax.swing.JPanel();
        spinnerColumns = new javax.swing.JSpinner();
        spinnerRows = new javax.swing.JSpinner();
        lblColumns = new javax.swing.JLabel();
        lblRows = new javax.swing.JLabel();
        jpContents = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstContentsAvailableContentItems = new javax.swing.JList<>();
        jspListContentsAssignedComponents = new javax.swing.JScrollPane();
        listContentsAssignedContentItems = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableContentsAssignedContentItems = new javax.swing.JTable();
        btnContentsRemoveContentItemFromList = new javax.swing.JButton();
        btnContentsAssignContentItemToList = new javax.swing.JButton();
        btnContentsAssignContentItemToTable = new javax.swing.JButton();
        btnContentsRemoveContentItemFromTable = new javax.swing.JButton();
        jpGeneration = new javax.swing.JPanel();
        txtfFilepath = new javax.swing.JTextField();
        btnFilepath = new javax.swing.JButton();
        txtfFilename = new javax.swing.JTextField();
        btnFilename = new javax.swing.JButton();
        btnGenerateReport = new javax.swing.JButton();
        jpGenerateReport = new javax.swing.JPanel();
        rbtnDocx = new javax.swing.JRadioButton();
        rbtnDocxAndPdf = new javax.swing.JRadioButton();
        rbtnPdf = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generate Report");

        jpProfile.setBorder(javax.swing.BorderFactory.createTitledBorder("Profile"));

        btnNewProfile.setText("New");

        btnLoadProfile.setText("Load");

        btnDeleteProfile.setText("Delete");

        btnSaveProfile.setText("Save");

        listProfile.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Syllabus" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listProfile.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scpListProfile.setViewportView(listProfile);

        javax.swing.GroupLayout jpProfileLayout = new javax.swing.GroupLayout(jpProfile);
        jpProfile.setLayout(jpProfileLayout);
        jpProfileLayout.setHorizontalGroup(
            jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProfileLayout.createSequentialGroup()
                        .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNewProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSaveProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeleteProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(btnLoadProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(scpListProfile))
                .addContainerGap())
        );
        jpProfileLayout.setVerticalGroup(
            jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProfileLayout.createSequentialGroup()
                .addComponent(scpListProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoadProfile)
                    .addComponent(btnNewProfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveProfile)
                    .addComponent(btnDeleteProfile))
                .addContainerGap())
        );

        jpClass.setBorder(javax.swing.BorderFactory.createTitledBorder("Class"));

        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IST" }));

        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "261" }));

        cmbSection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "001" }));

        lblDepartment.setText("Department:");

        lblCourse.setText("Course: ");

        lblSection.setText("Section:");

        javax.swing.GroupLayout jpClassLayout = new javax.swing.GroupLayout(jpClass);
        jpClass.setLayout(jpClassLayout);
        jpClassLayout.setHorizontalGroup(
            jpClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDepartment)
                .addGap(4, 4, 4)
                .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpClassLayout.setVerticalGroup(
            jpClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClassLayout.createSequentialGroup()
                .addGroup(jpClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourse)
                    .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSection)
                    .addComponent(cmbSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        listTemplateDefaultComponents.setBorder(javax.swing.BorderFactory.createTitledBorder("Default Components"));
        listTemplateDefaultComponents.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ASSIGNMENT", "CLASS_NAME", "COURSE_DESCRIPTION", "PROJECT_INDIVIDUAL", "PROJECT_GROUP", "RESOURCE_REQUIREMENTS{COLUMNS,ROWS}", "SCHEDULE{COLUMNS,ROWS}" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listTemplateDefaultComponents.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listTemplateDefaultComponents);

        listTemplateComponents.setBorder(javax.swing.BorderFactory.createTitledBorder("Template Components"));
        listTemplateComponents.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CLASS_NAME", "COURSE_DESCRIPTION", "CONTACT_INFORMATION", "RESOURCE_REQUIREMENTS{3,1}", "SCHEDULE{2,3}" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listTemplateComponents.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listTemplateComponents.setToolTipText("");
        jScrollPane3.setViewportView(listTemplateComponents);

        btnTemplateAddComponentToTemplate.setText(">>");

        btnTemplateRemoveComponentFromTemplate.setText("<<");

        tableTemplateTableContents.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tableTemplateTableContents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"DATE", "ASSIGNMENT"},
                {"DATE", "ASSIGNMENT"},
                {"DATE", "ASSIGNMENT"}
            },
            new String [] {
                "Column1", "Column2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableTemplateTableContents);

        btnAddComponentToTable.setText(">>");

        btnRemoveComponentFromTable.setText("<<");
        btnRemoveComponentFromTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveComponentFromTableActionPerformed(evt);
            }
        });

        jpTemplateTableSize.setBorder(javax.swing.BorderFactory.createTitledBorder("Table Size"));

        lblColumns.setText("Columns:");

        lblRows.setText("Rows:");

        javax.swing.GroupLayout jpTemplateTableSizeLayout = new javax.swing.GroupLayout(jpTemplateTableSize);
        jpTemplateTableSize.setLayout(jpTemplateTableSizeLayout);
        jpTemplateTableSizeLayout.setHorizontalGroup(
            jpTemplateTableSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTemplateTableSizeLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(lblColumns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblRows)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jpTemplateTableSizeLayout.setVerticalGroup(
            jpTemplateTableSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTemplateTableSizeLayout.createSequentialGroup()
                .addGroup(jpTemplateTableSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColumns)
                    .addComponent(lblRows))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpTemplateLayout = new javax.swing.GroupLayout(jpTemplate);
        jpTemplate.setLayout(jpTemplateLayout);
        jpTemplateLayout.setHorizontalGroup(
            jpTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTemplateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnTemplateAddComponentToTemplate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTemplateRemoveComponentFromTemplate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddComponentToTable))
                    .addComponent(btnRemoveComponentFromTable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpTemplateTableSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpTemplateLayout.setVerticalGroup(
            jpTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTemplateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jpTemplateLayout.createSequentialGroup()
                        .addGroup(jpTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpTemplateLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpTemplateTableSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpTemplateLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnTemplateAddComponentToTemplate)
                                .addGap(18, 18, 18)
                                .addComponent(btnTemplateRemoveComponentFromTemplate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpTemplateLayout.createSequentialGroup()
                                .addComponent(btnAddComponentToTable)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemoveComponentFromTable)
                                .addGap(0, 60, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Template", jpTemplate);

        lstContentsAvailableContentItems.setBorder(javax.swing.BorderFactory.createTitledBorder("Unassigned Content Items"));
        lstContentsAvailableContentItems.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ASSIGNMENT1", "ASSIGNMENT4", "ASSIGNMENT5", "PROJECT_GROUP1", "PROJECT_INDIVIDUAL1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstContentsAvailableContentItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(lstContentsAvailableContentItems);

        listContentsAssignedContentItems.setBorder(javax.swing.BorderFactory.createTitledBorder("Assigned Content Items"));
        listContentsAssignedContentItems.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CLASS_NAME", "COURSE_DESCRIPTION", "CONTACT_INFORMATION", "RESOURCE_REQUIREMENTS{3,1}", "SCHEDULE{2,3}" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listContentsAssignedContentItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jspListContentsAssignedComponents.setViewportView(listContentsAssignedContentItems);

        tableContentsAssignedContentItems.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tableContentsAssignedContentItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"April 10", "ASSIGNMENT2"},
                {"April 12", "ASSIGNMENT3"},
                {"April 14", "ASSIGNMENT6"}
            },
            new String [] {
                "Date", "Task"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tableContentsAssignedContentItems);

        btnContentsRemoveContentItemFromList.setText(">>");

        btnContentsAssignContentItemToList.setText("<<");

        btnContentsAssignContentItemToTable.setText("<<");
        btnContentsAssignContentItemToTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContentsAssignContentItemToTableActionPerformed(evt);
            }
        });

        btnContentsRemoveContentItemFromTable.setText(">>");

        javax.swing.GroupLayout jpContentsLayout = new javax.swing.GroupLayout(jpContents);
        jpContents.setLayout(jpContentsLayout);
        jpContentsLayout.setHorizontalGroup(
            jpContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpContentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jspListContentsAssignedComponents, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnContentsRemoveContentItemFromList)
                    .addComponent(btnContentsAssignContentItemToList)
                    .addComponent(btnContentsAssignContentItemToTable)
                    .addComponent(btnContentsRemoveContentItemFromTable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpContentsLayout.setVerticalGroup(
            jpContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpContentsLayout.createSequentialGroup()
                        .addComponent(jspListContentsAssignedComponents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jpContentsLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnContentsAssignContentItemToList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnContentsRemoveContentItemFromList)
                        .addGap(124, 124, 124)
                        .addComponent(btnContentsAssignContentItemToTable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnContentsRemoveContentItemFromTable)
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Contents", jpContents);

        txtfFilepath.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfFilepathFocusLost(evt);
            }
        });
        txtfFilepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfFilepathActionPerformed(evt);
            }
        });

        btnFilepath.setText("Change Filepath");
        btnFilepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilepathActionPerformed(evt);
            }
        });

        txtfFilename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfFilenameFocusLost(evt);
            }
        });
        txtfFilename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfFilenameActionPerformed(evt);
            }
        });

        btnFilename.setText("Change Filename");
        btnFilename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilenameActionPerformed(evt);
            }
        });

        btnGenerateReport.setText("Generate Report");
        btnGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportActionPerformed(evt);
            }
        });

        jpGenerateReport.setBorder(javax.swing.BorderFactory.createTitledBorder("Filetype"));

        buttonGroup1.add(rbtnDocx);
        rbtnDocx.setText("DOCX");
        rbtnDocx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDocxActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnDocxAndPdf);
        rbtnDocxAndPdf.setSelected(true);
        rbtnDocxAndPdf.setText("DOCX + PDF");

        buttonGroup1.add(rbtnPdf);
        rbtnPdf.setText("PDF");

        javax.swing.GroupLayout jpGenerateReportLayout = new javax.swing.GroupLayout(jpGenerateReport);
        jpGenerateReport.setLayout(jpGenerateReportLayout);
        jpGenerateReportLayout.setHorizontalGroup(
            jpGenerateReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGenerateReportLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(rbtnDocx)
                .addGap(60, 60, 60)
                .addComponent(rbtnDocxAndPdf)
                .addGap(75, 75, 75)
                .addComponent(rbtnPdf)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jpGenerateReportLayout.setVerticalGroup(
            jpGenerateReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGenerateReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbtnDocx)
                .addComponent(rbtnDocxAndPdf)
                .addComponent(rbtnPdf))
        );

        javax.swing.GroupLayout jpGenerationLayout = new javax.swing.GroupLayout(jpGeneration);
        jpGeneration.setLayout(jpGenerationLayout);
        jpGenerationLayout.setHorizontalGroup(
            jpGenerationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGenerationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpGenerationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGenerationLayout.createSequentialGroup()
                        .addGroup(jpGenerationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfFilename)
                            .addComponent(txtfFilepath))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpGenerationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFilepath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFilename, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jpGenerateReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpGenerationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerateReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpGenerationLayout.setVerticalGroup(
            jpGenerationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGenerationLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jpGenerationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfFilepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilepath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jpGenerationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilename))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jpGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnGenerateReport)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Generation", jpGeneration);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jpClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1))
                    .addComponent(jpProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Pick a new filepath to save reports in. (Doesn't pick files themselves, unless pointing at a folder to save in.) If invalid, changes aren't saved.
     * @param evt 
     */
    private void btnFilepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilepathActionPerformed
        try
        {
            JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            fc.setCurrentDirectory(new File(AppConstants.ROOT_FOLDER) );
            int intFileChooserReturnValue = fc.showOpenDialog(this);
            
            if (intFileChooserReturnValue == JFileChooser.APPROVE_OPTION)   //if filepath is valid
            {
                //File file = fc.getSelectedFile();
                //File fileFilepath = fc.getCurrentDirectory();
                //strFilepath = fileFilepath.getPath();     //getCurrentDirectory() and getPath() return a filepath that's one level too short (e.g., path is CourseManagement/resources, it will save it as CourseManagement instead)
                strFilepath = fc.getSelectedFile().toString() + "/";
                txtfFilepath.setText(strFilepath);
            }
            else if (intFileChooserReturnValue == JFileChooser.ERROR_OPTION)
            {
                throw new Exception();  //not sure what pops error, but if one can choose an invalid filepath, then maybe pop an error dialog about invalid target?
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFilepathActionPerformed

    /**
     * Generates a report.
     * TODO: report data gets passed in how and where?
     * @param evt 
     */
    private void btnGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportActionPerformed
        /*
        TODO
        try
        {
            //check if filepath is valid
            //check if filename is valid
            //check if data getting passed is valid here, I guess
            //if file already exists
            //  then ask if user wants to overwrite the preexisting file (default selection is "no")
            //      if true
            //          if file is (over)writeable ((and location can be written to))
            //              try to overwrite preexisting file with passed-in data
            //                  pop dialog stating "Report generated!"
            //              catch any errors for whatever reason with an error dialog
            //          otherwise
            //              pop error dialog stating "Report generation failed!", that the file cannot be overwritten or location cannot be written to or whatever, and with error log
            //otherwise
            //  if location can be written to
            //      try to write to file with passed-in data
            //          pop dialog stating "Report generated!"
            //      catch any errors for whatever reason with an error dialog with error log
            //  otherwise
            //      pop error dialog stating "Report generation failed!", that the file cannot be overwritten or location cannot be written to or whatever, and with error log
            
            //TODO: Possibly if a lot of reports get generated in short order, instead of dialog boxes, just pop colored labels to reduce clicking
            //Also a bunch of radio buttons for filetype(s). i.e., PDF, DOCX, or both.
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        */
    }//GEN-LAST:event_btnGenerateReportActionPerformed

    /**
     * Pick a new filename, either from preexisting ones on the computer or enter your own.
     * File extensions (i.e., anything after the first period (.) ) will be stripped in preparation for generation as a DOCX, PDF, or both.
     * @param evt 
     */
    private void btnFilenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilenameActionPerformed
        /*
        TODO
        rather than pulling from wherever JFileChooser decides to start from,
        check if current string in textbook is valid (since it can be typed in, not just FileChooser picked)
        if valid, start there
        otherwise, start from default location
        should also be able to enter a new one in JFileChooser for future generation,
        just as FileChoosers in other programs allow one to "reserve" a namespace without an actual preexisting file
        */
                try
        {
            JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
//            fc.setFileFilter(new FileFilter()
//                {
//                    public String getDescription()
//                    {
//                        return "PDF (*.pdf)";
//                    }
//                    
//                    public boolean accept(File f)
//                    {
//                        if (f.isDirectory() )
//                        {
//                            return true;
//                        }
//                        else
//                        {
//                            String filename = f.getName().toLowerCase();
//                            return filename.endsWith(".pdf");
//                        }
//                    }
//                });
            fc.addChoosableFileFilter(new FileNameExtensionFilter("DOCX (*.docx)", "docx"));
            fc.addChoosableFileFilter(new FileNameExtensionFilter("PDF (*.pdf)", "pdf"));
            fc.setAcceptAllFileFilterUsed(false);
            fc.setCurrentDirectory(new File(AppConstants.ROOT_FOLDER) );
            int intFileChooserReturnValue = fc.showSaveDialog(this);    //SAVE dialog means names can be "reserved" without the file actually existing
            
            if (intFileChooserReturnValue == JFileChooser.APPROVE_OPTION)   //if filepath is valid
            {
                File fileFilename = fc.getSelectedFile();
                if (fileFilename.getName().contains(".") == true)
                {
                    strFilename = fileFilename.getName().substring(0, fileFilename.getName().indexOf(".") );    //gets the filename without the file extension
                }
                else
                {
                    strFilename = fileFilename.getName();
                }
                txtfFilename.setText(strFilename);
            }
            else if (intFileChooserReturnValue == JFileChooser.ERROR_OPTION)
            {
                throw new Exception();  //not sure what pops error, but if one can choose an invalid filepath, then maybe pop an error dialog about invalid target?
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFilenameActionPerformed

    private void txtfFilenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfFilenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfFilenameActionPerformed

    private void txtfFilepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfFilepathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfFilepathActionPerformed

    /**
     * TODO: Check that having this focused and then say, clicking on Generate Report updates the variables correctly before btnGenerateReport fires.
     * @param evt 
     */
    private void txtfFilepathFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfFilepathFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfFilepathFocusLost

    /**
     * TODO: Check that having this focused and then say, clicking on Generate Report updates the variables correctly before btnGenerateReport fires.
     * @param evt 
     */
    private void txtfFilenameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfFilenameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfFilenameFocusLost

    private void btnContentsAssignContentItemToTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContentsAssignContentItemToTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContentsAssignContentItemToTableActionPerformed

    private void rbtnDocxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDocxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDocxActionPerformed

    private void btnRemoveComponentFromTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveComponentFromTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveComponentFromTableActionPerformed

//    for testing/debugging in isolation
//    /**
//     * @param args the command line arguments
//     */
//        public static void main(String[] args) {
//            
//        jfReport test = new jfReport();
//        test.setVisible(true);
//        
//
//        } //main
        
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportFrame().setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddComponentToTable;
    private javax.swing.JButton btnContentsAssignContentItemToList;
    private javax.swing.JButton btnContentsAssignContentItemToTable;
    private javax.swing.JButton btnContentsRemoveContentItemFromList;
    private javax.swing.JButton btnContentsRemoveContentItemFromTable;
    private javax.swing.JButton btnDeleteProfile;
    private javax.swing.JButton btnFilename;
    private javax.swing.JButton btnFilepath;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnLoadProfile;
    private javax.swing.JButton btnNewProfile;
    private javax.swing.JButton btnRemoveComponentFromTable;
    private javax.swing.JButton btnSaveProfile;
    private javax.swing.JButton btnTemplateAddComponentToTemplate;
    private javax.swing.JButton btnTemplateRemoveComponentFromTemplate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JComboBox<String> cmbSection;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpClass;
    private javax.swing.JPanel jpContents;
    private javax.swing.JPanel jpGenerateReport;
    private javax.swing.JPanel jpGeneration;
    private javax.swing.JPanel jpProfile;
    private javax.swing.JPanel jpTemplate;
    private javax.swing.JPanel jpTemplateTableSize;
    private javax.swing.JScrollPane jspListContentsAssignedComponents;
    private javax.swing.JLabel lblColumns;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblRows;
    private javax.swing.JLabel lblSection;
    private javax.swing.JList<String> listContentsAssignedContentItems;
    private javax.swing.JList<String> listProfile;
    private javax.swing.JList<String> listTemplateComponents;
    private javax.swing.JList<String> listTemplateDefaultComponents;
    private javax.swing.JList<String> lstContentsAvailableContentItems;
    private javax.swing.JRadioButton rbtnDocx;
    private javax.swing.JRadioButton rbtnDocxAndPdf;
    private javax.swing.JRadioButton rbtnPdf;
    private javax.swing.JScrollPane scpListProfile;
    private javax.swing.JSpinner spinnerColumns;
    private javax.swing.JSpinner spinnerRows;
    private javax.swing.JTable tableContentsAssignedContentItems;
    private javax.swing.JTable tableTemplateTableContents;
    private javax.swing.JTextField txtfFilename;
    private javax.swing.JTextField txtfFilepath;
    // End of variables declaration//GEN-END:variables
}
