/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.psu.berksist.CourseEZ;

import java.sql.Connection;

/**
 *
 * @author Nicholas
 */
public class jpAddBook extends javax.swing.JPanel {

    private Connection dbConnection;
    
    /**
     * Creates new form jpAddBook
     */
    public jpAddBook() {
        initComponents();
    }
    
    public jpAddBook(Connection inConnection)
    {
        initComponents();
        dbConnection = inConnection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jlTitle = new javax.swing.JLabel();
        jlAuthor = new javax.swing.JLabel();
        jlISBN = new javax.swing.JLabel();
        jlWebsite = new javax.swing.JLabel();
        jlPublisher = new javax.swing.JLabel();
        jlClass = new javax.swing.JLabel();
        jtfPublisher = new javax.swing.JTextField();
        jtfClass = new javax.swing.JTextField();
        jtfClass1 = new javax.swing.JTextField();
        jtfISBN = new javax.swing.JTextField();
        jtfAuthor = new javax.swing.JTextField();
        jlPrice = new javax.swing.JLabel();
        jtfPrice = new javax.swing.JTextField();
        jlRequired = new javax.swing.JLabel();
        jtfRequired = new javax.swing.JTextField();
        jlOptional = new javax.swing.JLabel();
        jtfOptional = new javax.swing.JTextField();
        jlPowerpoints = new javax.swing.JLabel();
        jtfPowerpoints = new javax.swing.JTextField();
        jlSolutions = new javax.swing.JLabel();
        jtfSolutions = new javax.swing.JTextField();
        jlTests = new javax.swing.JLabel();
        jtfTests = new javax.swing.JTextField();
        jlManual = new javax.swing.JLabel();
        jtfManual = new javax.swing.JTextField();
        jbSave = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jspCourses = new javax.swing.JScrollPane();
        jListCourses = new javax.swing.JList<>();
        jLabelCourses = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtfTitle = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        jlTitle.setText("Title : ");

        jlAuthor.setText("Author : ");

        jlISBN.setText("ISBN : ");

        jlWebsite.setText("Website : ");

        jlPublisher.setText("Publisher : ");

        jlClass.setText("Edition :");

        jtfPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPublisherActionPerformed(evt);
            }
        });

        jtfClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfClassActionPerformed(evt);
            }
        });

        jtfClass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfClass1ActionPerformed(evt);
            }
        });

        jlPrice.setText("Price : ");

        jtfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPriceActionPerformed(evt);
            }
        });

        jlRequired.setText("Required : ");

        jlOptional.setText("Optional : ");

        jlPowerpoints.setText("Powerpoints : ");

        jlSolutions.setText("Solutions : ");

        jlTests.setText("Tests : ");

        jlManual.setText("Manual :");

        jbSave.setText("Save");

        jbCancel.setText("Cancel");

        jListCourses.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jspCourses.setViewportView(jListCourses);

        jLabelCourses.setText("Courses :");

        jButton1.setText("Add Course");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSave, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlRequired)
                                .addGap(18, 18, 18)
                                .addComponent(jtfRequired))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAuthor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfAuthor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlISBN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfISBN))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlWebsite)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfClass1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlPublisher)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlClass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfClass, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlOptional)
                                .addGap(32, 32, 32)
                                .addComponent(jtfOptional)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCourses)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jspCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlPrice)
                                .addGap(18, 18, 18)
                                .addComponent(jtfPrice))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlPowerpoints)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfPowerpoints, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlSolutions)
                                .addGap(18, 18, 18)
                                .addComponent(jtfSolutions))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlTests)
                                .addGap(18, 18, 18)
                                .addComponent(jtfTests))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlManual)
                                .addGap(18, 18, 18)
                                .addComponent(jtfManual)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlTitle)
                        .addGap(18, 18, 18)
                        .addComponent(jtfTitle)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTitle)
                    .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAuthor)
                    .addComponent(jtfAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPrice)
                    .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlISBN)
                    .addComponent(jtfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPowerpoints)
                    .addComponent(jtfPowerpoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlWebsite)
                    .addComponent(jtfClass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSolutions)
                    .addComponent(jtfSolutions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPublisher)
                    .addComponent(jtfPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTests)
                    .addComponent(jtfTests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlClass)
                    .addComponent(jtfClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlManual)
                    .addComponent(jtfManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCourses)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlRequired)
                            .addComponent(jtfRequired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlOptional)
                            .addComponent(jtfOptional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jspCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSave)
                    .addComponent(jbCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPublisherActionPerformed

    private void jtfClass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfClass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfClass1ActionPerformed

    private void jtfPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPriceActionPerformed

    private void jtfClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfClassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelCourses;
    private javax.swing.JList<String> jListCourses;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbSave;
    private javax.swing.JLabel jlAuthor;
    private javax.swing.JLabel jlClass;
    private javax.swing.JLabel jlISBN;
    private javax.swing.JLabel jlManual;
    private javax.swing.JLabel jlOptional;
    private javax.swing.JLabel jlPowerpoints;
    private javax.swing.JLabel jlPrice;
    private javax.swing.JLabel jlPublisher;
    private javax.swing.JLabel jlRequired;
    private javax.swing.JLabel jlSolutions;
    private javax.swing.JLabel jlTests;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JLabel jlWebsite;
    private javax.swing.JScrollPane jspCourses;
    private javax.swing.JTextField jtfAuthor;
    private javax.swing.JTextField jtfClass;
    private javax.swing.JTextField jtfClass1;
    private javax.swing.JTextField jtfISBN;
    private javax.swing.JTextField jtfManual;
    private javax.swing.JTextField jtfOptional;
    private javax.swing.JTextField jtfPowerpoints;
    private javax.swing.JTextField jtfPrice;
    private javax.swing.JTextField jtfPublisher;
    private javax.swing.JTextField jtfRequired;
    private javax.swing.JTextField jtfSolutions;
    private javax.swing.JTextField jtfTests;
    private javax.swing.JTextField jtfTitle;
    // End of variables declaration//GEN-END:variables
}
