package org.psu.berksist.CourseEZ;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author Robert Zwolinski
 */
public class jpMain extends javax.swing.JPanel {

    int intWindowCounter = 0;
    
    public Connection dbConnection;
    public DBConnection dbc;
    
    private TileAction taTile;
    
    
    /**
     * Creates new form jpMain
     */
    public jpMain() 
    {
        initComponents();
        taTile.setDesktop(jdpMain);
        
        dbc = new DBConnection(this);
        
        
    }
    
    public void CreateFrame() {

        JPanel jpTemp = new JPanel();
        jpTemp.setPreferredSize(new Dimension(200, 200));

        CreateFrame(jpTemp, "");

    } // CreateFrame

    public void CreateFrame(JPanel jpIn, String strIn) {
        intWindowCounter++;

        JInternalFrame jifTemp = new JInternalFrame(strIn, true, true, true, true);

        jifTemp.add(jpIn);
        jifTemp.pack();

        jdpMain.add(jifTemp);
        jifTemp.setVisible(true);

    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbDocuments = new javax.swing.JButton();
        jbAssignments = new javax.swing.JButton();
        jbCourse = new javax.swing.JButton();
        jbClass = new javax.swing.JButton();
        jtbMain = new javax.swing.JToolBar();
        jbAddFrame = new javax.swing.JButton();
        jbTile = new javax.swing.JButton(taTile = new TileAction());
        jdpMain = new javax.swing.JDesktopPane();
        jbBooks = new javax.swing.JButton();

        jbDocuments.setText("Resources");
        jbDocuments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDocumentsActionPerformed(evt);
            }
        });

        jbAssignments.setText("Assignments");
        jbAssignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAssignmentsActionPerformed(evt);
            }
        });

        jbCourse.setText("Course");
        jbCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCourseActionPerformed(evt);
            }
        });

        jbClass.setText("Class");
        jbClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClassActionPerformed(evt);
            }
        });

        jtbMain.setFloatable(false);
        jtbMain.setRollover(true);
        jtbMain.setToolTipText("");

        jbAddFrame.setText("Add");
        jbAddFrame.setToolTipText("Create and add new window");
        jbAddFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddFrameActionPerformed(evt);
            }
        });
        jtbMain.add(jbAddFrame);

        jbTile.setText("");
        jbTile.setToolTipText("");
        jbTile.setFocusable(false);
        jbTile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbTile.setIconTextGap(-17);
        jbTile.setMinimumSize(new java.awt.Dimension(36, 36));
        jbTile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbMain.add(jbTile);

        javax.swing.GroupLayout jdpMainLayout = new javax.swing.GroupLayout(jdpMain);
        jdpMain.setLayout(jdpMainLayout);
        jdpMainLayout.setHorizontalGroup(
            jdpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jdpMainLayout.setVerticalGroup(
            jdpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );

        jbBooks.setText("Books");
        jbBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBooksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jdpMain)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbCourse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAssignments)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDocuments)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBooks)
                        .addGap(18, 18, 18)
                        .addComponent(jtbMain, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbCourse)
                        .addComponent(jbClass)
                        .addComponent(jbAssignments)
                        .addComponent(jbDocuments)
                        .addComponent(jbBooks))
                    .addComponent(jtbMain, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdpMain)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbDocumentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDocumentsActionPerformed
        JPanel Resources = new jpResources(dbConnection);
        Resources.setName("Resources");
        CreateFrame(Resources, Resources.getName());
    }//GEN-LAST:event_jbDocumentsActionPerformed

    private void jbAssignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAssignmentsActionPerformed
        JPanel Assignment = new jpAssignment(dbConnection);
        Assignment.setName("Assignment");
        CreateFrame(Assignment, Assignment.getName());
    }//GEN-LAST:event_jbAssignmentsActionPerformed

    private void jbCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCourseActionPerformed
        JPanel Course = new jpCourse(dbConnection);
        Course.setName("Course");
        CreateFrame(Course, Course.getName());

    }//GEN-LAST:event_jbCourseActionPerformed

    private void jbClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClassActionPerformed
        JPanel Class = new jpClass(dbConnection);
        Class.setName("Class");
        CreateFrame(Class, Class.getName());

    }//GEN-LAST:event_jbClassActionPerformed

    private void jbAddFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddFrameActionPerformed

        CreateFrame();

    }//GEN-LAST:event_jbAddFrameActionPerformed

    private void jbBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBooksActionPerformed
        JPanel Book = new jpBook(dbConnection);
        Book.setName("Book");
        CreateFrame(Book, Book.getName());
    }//GEN-LAST:event_jbBooksActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAddFrame;
    private javax.swing.JButton jbAssignments;
    private javax.swing.JButton jbBooks;
    private javax.swing.JButton jbClass;
    private javax.swing.JButton jbCourse;
    private javax.swing.JButton jbDocuments;
    public javax.swing.JButton jbTile;
    public javax.swing.JDesktopPane jdpMain;
    private javax.swing.JToolBar jtbMain;
    // End of variables declaration//GEN-END:variables
}
