/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.psu.berksist.CourseEZ;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author whb108
 */
public class jpSQLiteDBInfo extends javax.swing.JPanel {

    /**
     * Creates new form jpSQLiteDBInfo
     */
    public jpSQLiteDBInfo(Connection inConnection, Properties myProps) 
    {
        
        try {
            DatabaseMetaData dbmdInfo = inConnection.getMetaData();
            if (dbmdInfo.getDatabaseProductName().equals("SQLite") == false)
            {
                JOptionPane.showMessageDialog(this,
                        "The Connection is not a SQLite database!",
                        "Not a SQLite DB", JOptionPane.ERROR_MESSAGE);
                return;
            }
            else
            {
               initComponents();
               jtaDBName.setText(myProps.getProperty(AppConstants.LAST_DB));
jtfDBProductName.setText(dbmdInfo.getDatabaseProductName());
jtfDBProductVersion.setText(dbmdInfo.getDatabaseProductVersion());
jtfDBMajorVersion.setText(Integer.toString(dbmdInfo.getDatabaseMajorVersion()));
jtfDBMinorVersion.setText(Integer.toString(dbmdInfo.getDatabaseMinorVersion()));


jtfDriverName.setText(dbmdInfo.getDriverName());                            
jtfDriverVersion.setText(dbmdInfo.getDriverVersion());
jtfDriverMajorVersion.setText(Integer.toString(dbmdInfo.getDriverMajorVersion()));
jtfDriverMinorVersion.setText(Integer.toString(dbmdInfo.getDriverMinorVersion()));
// dbmdInfo.getJDBCMajorVersion();

Statement stmtTables = inConnection.createStatement();
ResultSet rsTables = stmtTables.executeQuery("SELECT name FROM sqlite_master WHERE type='table' order by name");

 while (rsTables.next() == true)
 {
    jtaTables.append(rsTables.getString(1) + "\n");
 }
jtaTables.setCaretPosition(0);

ResultSet rsViews = stmtTables.executeQuery("SELECT name FROM sqlite_master WHERE type='view' order by name");
          
             while (rsViews.next() == true)
 {
    jtaViews.append(rsViews.getString(1) + "\n");
 }
jtaViews.setCaretPosition(0);
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(jpSQLiteDBInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jtfDBProductName = new javax.swing.JTextField();
        jlProductName = new javax.swing.JLabel();
        jtfDBProductVersion = new javax.swing.JTextField();
        jlProductVersion = new javax.swing.JLabel();
        jtfDBMajorVersion = new javax.swing.JTextField();
        jlDBMajorVersion = new javax.swing.JLabel();
        jtfDBMinorVersion = new javax.swing.JTextField();
        jlDBMinorVersion = new javax.swing.JLabel();
        jtfDriverName = new javax.swing.JTextField();
        jtfDriverVersion = new javax.swing.JTextField();
        jtfDriverMajorVersion = new javax.swing.JTextField();
        jtfDriverMinorVersion = new javax.swing.JTextField();
        jlDriverName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlDriverVersion = new javax.swing.JLabel();
        jlDriverMajorVersion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlDBName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaDBName = new javax.swing.JTextArea();
        jlTables = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaTables = new javax.swing.JTextArea();
        jlViews = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtaViews = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jtfDBProductName.setEditable(false);
        jtfDBProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDBProductNameActionPerformed(evt);
            }
        });

        jlProductName.setLabelFor(jtfDBProductName);
        jlProductName.setText("Name");

        jtfDBProductVersion.setEditable(false);
        jtfDBProductVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDBProductVersionActionPerformed(evt);
            }
        });

        jlProductVersion.setLabelFor(jtfDBProductVersion);
        jlProductVersion.setText("Version");

        jtfDBMajorVersion.setEditable(false);
        jtfDBMajorVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDBMajorVersionActionPerformed(evt);
            }
        });

        jlDBMajorVersion.setText("Major Version");

        jtfDBMinorVersion.setEditable(false);
        jtfDBMinorVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDBMinorVersionActionPerformed(evt);
            }
        });

        jlDBMinorVersion.setLabelFor(jtfDBMinorVersion);
        jlDBMinorVersion.setText("Minor Version");

        jlDriverName.setText("Name");

        jLabel1.setText("Product Information");

        jLabel2.setText("Driver Information");

        jlDriverVersion.setLabelFor(jtfDriverVersion);
        jlDriverVersion.setText("Version");

        jlDriverMajorVersion.setLabelFor(jtfDriverMajorVersion);
        jlDriverMajorVersion.setText("Major Version");

        jLabel5.setLabelFor(jtfDriverMinorVersion);
        jLabel5.setText("Minor Version");

        jlDBName.setLabelFor(jtaDBName);
        jlDBName.setText("Database File");

        jtaDBName.setColumns(20);
        jtaDBName.setRows(5);
        jScrollPane2.setViewportView(jtaDBName);

        jlTables.setText("Tables");

        jtaTables.setColumns(20);
        jtaTables.setRows(5);
        jScrollPane3.setViewportView(jtaTables);

        jlViews.setText("Views");

        jtaViews.setColumns(20);
        jtaViews.setRows(5);
        jScrollPane4.setViewportView(jtaViews);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlDBName)
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlTables)
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlProductName)
                                            .addComponent(jlProductVersion)
                                            .addComponent(jlDBMajorVersion)
                                            .addComponent(jlDBMinorVersion))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfDBMajorVersion)
                                            .addComponent(jtfDBProductVersion)
                                            .addComponent(jtfDBProductName)
                                            .addComponent(jtfDBMinorVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jlDriverMajorVersion))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfDriverMajorVersion)
                                            .addComponent(jtfDriverVersion)
                                            .addComponent(jtfDriverName)
                                            .addComponent(jtfDriverMinorVersion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jlDriverName)
                                    .addComponent(jlDriverVersion))))
                        .addGap(0, 314, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlViews)
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtfDriverMajorVersion, jtfDriverMinorVersion, jtfDriverName, jtfDriverVersion});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDBProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlProductName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDBProductVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlProductVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDBMajorVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDBMajorVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDBMinorVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDBMinorVersion))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDriverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDriverName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDriverVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDriverVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDriverMajorVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDriverMajorVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDriverMinorVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDBName)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTables)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlViews)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDBProductVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDBProductVersionActionPerformed
        
    }//GEN-LAST:event_jtfDBProductVersionActionPerformed

    private void jtfDBMajorVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDBMajorVersionActionPerformed
        
    }//GEN-LAST:event_jtfDBMajorVersionActionPerformed

    private void jtfDBMinorVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDBMinorVersionActionPerformed
        
    }//GEN-LAST:event_jtfDBMinorVersionActionPerformed

    private void jtfDBProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDBProductNameActionPerformed
        
    }//GEN-LAST:event_jtfDBProductNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlDBMajorVersion;
    private javax.swing.JLabel jlDBMinorVersion;
    private javax.swing.JLabel jlDBName;
    private javax.swing.JLabel jlDriverMajorVersion;
    private javax.swing.JLabel jlDriverName;
    private javax.swing.JLabel jlDriverVersion;
    private javax.swing.JLabel jlProductName;
    private javax.swing.JLabel jlProductVersion;
    private javax.swing.JLabel jlTables;
    private javax.swing.JLabel jlViews;
    private javax.swing.JTextArea jtaDBName;
    private javax.swing.JTextArea jtaTables;
    private javax.swing.JTextArea jtaViews;
    private javax.swing.JTextField jtfDBMajorVersion;
    private javax.swing.JTextField jtfDBMinorVersion;
    private javax.swing.JTextField jtfDBProductName;
    private javax.swing.JTextField jtfDBProductVersion;
    private javax.swing.JTextField jtfDriverMajorVersion;
    private javax.swing.JTextField jtfDriverMinorVersion;
    private javax.swing.JTextField jtfDriverName;
    private javax.swing.JTextField jtfDriverVersion;
    // End of variables declaration//GEN-END:variables
}
